/**
 * Depth levels based on Aron et al. (1997) escalation protocol:
 *  1 = Ligera  — fun memories, favorites, hypotheticals (safe, ice-breaker)
 *  2 = Media   — values, lessons, moderate self-disclosure
 *  3 = Profunda — vulnerability, forgiveness, fears, legacy
 */
export type QuestionDepth = 1 | 2 | 3;

export interface Question {
  id: string;
  question: string;
  translationUS: string;
  category: Category;
  /** Aron-style depth level (1=light, 2=moderate, 3=deep). Optional for
   *  backward compat with questions stored in localStorage before this
   *  field existed — defaults to 1 when missing. */
  depth?: QuestionDepth;
  /** Correct answer for trivia questions (Spanish). When present, the UI
   *  shows a "Reveal answer" button and Aron depth + Gottman appreciation
   *  mechanics are skipped (different game mode). */
  answer?: string;
  /** Correct answer in English. */
  answerUS?: string;
}

export enum Category {
  random = 'Aleatorio',
  goals = 'Metas y sueños personales',
  principles = 'Valores y principios importantes',
  challenges = 'Cambios y desafíos en la vida personal',
  relationships = 'Comunicación y relaciones interpersonales',
  education = 'Educación y desarrollo personal',
  health = 'Salud y bienestar físico y mental',
  money = 'Finanzas y administración del dinero',
  work = 'Carrera y desarrollo profesional',
  technology = 'Tecnología y su impacto en la vida cotidiana',
  news = 'Actualidad y eventos mundiales',
  community = 'Comunidad y responsabilidad social',
  environments = 'Medio ambiente y sustentabilidad',
  culture = 'Cultura y diversidad',
  spirituality = 'Espiritualidad y fe',
  freeTime = 'Planificación y organización del tiempo libre.',
  familyStories = 'Historias familiares',
  // ── Trivia categories (with answer field) ──
  triviaRandom = 'Trivia · Todas',
  triviaCountries = 'Trivia · Países',
  triviaCities = 'Trivia · Ciudades',
  triviaMusic = 'Trivia · Música',
  triviaFruits = 'Trivia · Frutas',
  triviaFootball = 'Trivia · Fútbol',
  triviaColors = 'Trivia · Colores',
}

export const defaultCategory = {
  [Category.random]: {
    name: Category.random,
    image: '/assets/categories/random.png',
  },
  [Category.goals]: {
    name: Category.goals,
    image: '/assets/categories/goals.png',
  },
  [Category.principles]: {
    name: Category.principles,
    image: '/assets/categories/principles.png',
  },
  [Category.challenges]: {
    name: Category.challenges,
    image: '/assets/categories/challenges.png',
  },
  [Category.relationships]: {
    name: Category.relationships,
    image: '/assets/categories/relationships.png',
  },
  [Category.education]: {
    name: Category.education,
    image: '/assets/categories/education.png',
  },
  [Category.health]: {
    name: Category.health,
    image: '/assets/categories/health.png',
  },
  [Category.money]: {
    name: Category.money,
    image: '/assets/categories/money.png',
  },
  [Category.work]: {
    name: Category.work,
    image: '/assets/categories/work.png',
  },
  [Category.technology]: {
    name: Category.technology,
    image: '/assets/categories/technology.png',
  },
  [Category.news]: {
    name: Category.news,
    image: '/assets/categories/news.png',
  },
  [Category.community]: {
    name: Category.community,
    image: '/assets/categories/community.png',
  },
  [Category.environments]: {
    name: Category.environments,
    image: '/assets/categories/environments.png',
  },
  [Category.culture]: {
    name: Category.culture,
    image: '/assets/categories/culture.png',
  },
  [Category.spirituality]: {
    name: Category.spirituality,
    image: '/assets/categories/spirituality.png',
  },
  [Category.freeTime]: {
    name: Category.freeTime,
    image: '/assets/categories/freeTime.png',
  },
  [Category.familyStories]: {
    name: Category.familyStories,
    image: '/assets/categories/familyStories.png',
  },
  [Category.triviaRandom]: {
    name: Category.triviaRandom,
    image: '/assets/categories/triviaRandom.png',
  },
  [Category.triviaCountries]: {
    name: Category.triviaCountries,
    image: '/assets/categories/triviaCountries.png',
  },
  [Category.triviaCities]: {
    name: Category.triviaCities,
    image: '/assets/categories/triviaCities.png',
  },
  [Category.triviaMusic]: {
    name: Category.triviaMusic,
    image: '/assets/categories/triviaMusic.png',
  },
  [Category.triviaFruits]: {
    name: Category.triviaFruits,
    image: '/assets/categories/triviaFruits.png',
  },
  [Category.triviaFootball]: {
    name: Category.triviaFootball,
    image: '/assets/categories/triviaFootball.png',
  },
  [Category.triviaColors]: {
    name: Category.triviaColors,
    image: '/assets/categories/triviaColors.png',
  },
};

export const defaultQuestionCounter = {
  [Category.random]: 0,
  [Category.goals]: 0,
  [Category.principles]: 0,
  [Category.challenges]: 0,
  [Category.relationships]: 0,
  [Category.education]: 0,
  [Category.health]: 0,
  [Category.money]: 0,
  [Category.work]: 0,
  [Category.technology]: 0,
  [Category.news]: 0,
  [Category.community]: 0,
  [Category.environments]: 0,
  [Category.culture]: 0,
  [Category.spirituality]: 0,
  [Category.freeTime]: 0,
  [Category.familyStories]: 0,
  [Category.triviaRandom]: 0,
  [Category.triviaCountries]: 0,
  [Category.triviaCities]: 0,
  [Category.triviaMusic]: 0,
  [Category.triviaFruits]: 0,
  [Category.triviaFootball]: 0,
  [Category.triviaColors]: 0,
};

// Questions rewritten with research-backed principles (Aron et al. 1997,
// Gottman Love Maps, Duke & Fivush "Do You Know?" scale): open-ended,
// anchored to specific memories/experiences, age-inclusive, reciprocal,
// and free of assumptions about parenthood, marital status or religion.
// IDs and categories preserved so existing localStorage keeps working.
export const questions: { [key: string]: Question } = {
  // ── Metas y sueños personales ─────────────────────────────────────
  '1': {
    id: '1',
    question: 'Cuando eras niño/a, ¿qué querías ser de grande? ¿Por qué?',
    translationUS: 'When you were a child, what did you want to be when you grew up? Why?',
    category: Category.goals,
    depth: 1,
  },
  '2': {
    id: '2',
    question: 'Si pudieras empezar de cero hoy sin miedo al fracaso, ¿qué intentarías?',
    translationUS: 'If you could start over today without fear of failure, what would you try?',
    category: Category.goals,
    depth: 2,
  },
  '3': {
    id: '3',
    question: '¿Cuál es un sueño que tienes y que casi nadie sabe?',
    translationUS: 'What is a dream you have that almost no one knows about?',
    category: Category.goals,
    depth: 3,
  },
  '4': {
    id: '4',
    question: '¿Hay algún sueño que soltaste? ¿Qué pasó?',
    translationUS: 'Is there a dream you let go of? What happened?',
    category: Category.goals,
    depth: 3,
  },
  '5': {
    id: '5',
    question: '¿Qué cosa pequeña lograste este año que te llenó de orgullo?',
    translationUS: 'What small thing did you achieve this year that made you proud?',
    category: Category.goals,
    depth: 1,
  },
  '6': {
    id: '6',
    question: '¿Dónde te imaginas en cinco años? ¿Qué estarías dispuesto/a a cambiar para llegar?',
    translationUS: 'Where do you see yourself in five years? What would you be willing to change to get there?',
    category: Category.goals,
    depth: 2,
  },
  '7': {
    id: '7',
    question: 'Cuéntanos de alguien cuya vida admiras. ¿Qué hace esa persona que te inspira?',
    translationUS: 'Tell us about someone whose life you admire. What do they do that inspires you?',
    category: Category.goals,
    depth: 1,
  },
  '8': {
    id: '8',
    question: 'Si tuvieras un año libre con todo pagado, ¿qué harías?',
    translationUS: 'If you had a year off with all expenses paid, what would you do?',
    category: Category.goals,
    depth: 1,
  },
  '9': {
    id: '9',
    question: '¿Qué habilidad te encantaría aprender si tuvieras tiempo?',
    translationUS: 'What skill would you love to learn if you had the time?',
    category: Category.goals,
    depth: 1,
  },
  '10': {
    id: '10',
    question: '¿Qué sería lo primero que harías si ganaras la lotería mañana?',
    translationUS: "What's the first thing you would do if you won the lottery tomorrow?",
    category: Category.goals,
    depth: 1,
  },

  // ── Valores y principios importantes ──────────────────────────────
  kjhf823h: {
    id: 'kjhf823h',
    question: 'Cuéntanos de una vez que elegiste hacer lo correcto aunque fue difícil.',
    translationUS: 'Tell us about a time you chose to do the right thing even though it was hard.',
    category: Category.principles,
    depth: 2,
  },
  iuhf9084: {
    id: 'iuhf9084',
    question: '¿Quién te enseñó tu valor más importante? ¿Cómo lo hizo?',
    translationUS: 'Who taught you your most important value? How did they teach it?',
    category: Category.principles,
    depth: 2,
  },
  lkjhg890: {
    id: 'lkjhg890',
    question: '¿Qué harías si encontraras una cartera llena de dinero en la calle?',
    translationUS: 'What would you do if you found a wallet full of money on the street?',
    category: Category.principles,
    depth: 1,
  },
  iuhg890: {
    id: 'iuhg890',
    question: '¿Hay algo en lo que crees firmemente que a otros les parece raro?',
    translationUS: 'Is there something you firmly believe that others find strange?',
    category: Category.principles,
    depth: 2,
  },
  hjg890s: {
    id: 'hjg890s',
    question: 'Cuéntanos de un momento en que alguien fue honesto contigo y te marcó.',
    translationUS: 'Tell us about a moment when someone was honest with you and it marked you.',
    category: Category.principles,
    depth: 2,
  },
  rtj890d: {
    id: 'rtj890d',
    question: '¿Qué regla de tu casa cuando eras niño/a sigue contigo hoy?',
    translationUS: 'What rule from your childhood home still lives with you today?',
    category: Category.principles,
    depth: 1,
  },
  yujh890h: {
    id: 'yujh890h',
    question: '¿Qué mentira pequeña consideras aceptable? ¿Cuál no?',
    translationUS: 'What small lie do you consider acceptable? Which one isn’t?',
    category: Category.principles,
    depth: 2,
  },
  kjhg890f: {
    id: 'kjhg890f',
    question: 'Cuéntanos de alguien que admiras por sus valores. ¿Qué hace esa persona?',
    translationUS: 'Tell us about someone you admire for their values. What do they do?',
    category: Category.principles,
    depth: 1,
  },
  iuhg890g: {
    id: 'iuhg890g',
    question: 'Si pudieras transmitir un solo valor a alguien importante para ti, ¿cuál sería y por qué?',
    translationUS: 'If you could pass on just one value to someone important to you, which would it be and why?',
    category: Category.principles,
    depth: 3,
  },
  lkjhg890h: {
    id: 'lkjhg890h',
    question: '¿Cuándo fue una ocasión en que te arrepentiste de no haber hablado?',
    translationUS: 'When was a time you regretted not speaking up?',
    category: Category.principles,
    depth: 3,
  },

  // ── Cambios y desafíos ────────────────────────────────────────────
  aabbcc111: {
    id: 'aabbcc111',
    question: '¿Cuál ha sido el cambio más grande de tu vida hasta ahora?',
    translationUS: 'What has been the biggest change in your life so far?',
    category: Category.challenges,
    depth: 2,
  },
  ss22bc121: {
    id: 'ss22bc121',
    question: 'Cuéntanos de un momento difícil que hoy agradeces haber vivido.',
    translationUS: "Tell us about a hard moment you're now grateful to have lived through.",
    category: Category.challenges,
    depth: 3,
  },
  dss21cc32: {
    id: 'dss21cc32',
    question: '¿Quién te ayudó en un momento duro y nunca se lo dijiste?',
    translationUS: 'Who helped you during a tough time and you never told them?',
    category: Category.challenges,
    depth: 3,
  },
  ssjj223311: {
    id: 'ssjj223311',
    question: '¿Qué te daba mucho miedo de niño/a que ya no te da?',
    translationUS: "What used to scare you a lot as a child that doesn't anymore?",
    category: Category.challenges,
    depth: 1,
  },
  aabbzz21c9: {
    id: 'aabbzz21c9',
    question: 'Cuéntanos un error que cometiste y qué aprendiste de él.',
    translationUS: 'Tell us about a mistake you made and what you learned from it.',
    category: Category.challenges,
    depth: 2,
  },
  ccdd33444a: {
    id: 'ccdd33444a',
    question: '¿Qué cosa dejaste atrás en el último año?',
    translationUS: 'What have you left behind in the last year?',
    category: Category.challenges,
    depth: 2,
  },
  dss22aabbb: {
    id: 'dss22aabbb',
    question: '¿Cómo supiste que alguien cercano estaba pasando por algo difícil? ¿Qué hiciste?',
    translationUS: 'How did you know someone close was going through something hard? What did you do?',
    category: Category.challenges,
    depth: 2,
  },
  ccdd33444c: {
    id: 'ccdd33444c',
    question: '¿Hay un "no" que recibiste que hoy agradeces?',
    translationUS: "Is there a 'no' you received that you're now thankful for?",
    category: Category.challenges,
    depth: 3,
  },
  eeff556677: {
    id: 'eeff556677',
    question: 'Si pudieras darte un consejo a ti mismo/a hace cinco años, ¿cuál sería?',
    translationUS: 'If you could give yourself advice five years ago, what would it be?',
    category: Category.challenges,
    depth: 2,
  },
  gg11hh22ii: {
    id: 'gg11hh22ii',
    question: '¿Qué cambio te gustaría hacer pero no te atreves?',
    translationUS: "What change would you like to make but you don't dare?",
    category: Category.challenges,
    depth: 3,
  },

  // ── Comunicación y relaciones interpersonales ─────────────────────
  kx6gph890: {
    id: 'kx6gph890',
    question: '¿Cuál es tu recuerdo más feliz con alguien que está aquí?',
    translationUS: 'What is your happiest memory with someone who is here right now?',
    category: Category.relationships,
    depth: 2,
  },
  f6p9bz111: {
    id: 'f6p9bz111',
    question: 'Dile a alguien en esta mesa algo que admiras de él/ella.',
    translationUS: 'Tell someone at this table something you admire about them.',
    category: Category.relationships,
    depth: 3,
  },
  '3u2gqv819': {
    id: '3u2gqv819',
    question: '¿Quién es la persona que mejor te conoce? ¿Qué sabe de ti que nadie más sabe?',
    translationUS: 'Who is the person who knows you best? What do they know about you that no one else does?',
    category: Category.relationships,
    depth: 2,
  },
  d5p7mq090: {
    id: 'd5p7mq090',
    question: 'Cuéntanos de un amigo/a que ya no ves pero que marcó tu vida.',
    translationUS: 'Tell us about a friend you no longer see but who marked your life.',
    category: Category.relationships,
    depth: 2,
  },
  gk9pfz819: {
    id: 'gk9pfz819',
    question: '¿Cómo muestras cariño sin palabras?',
    translationUS: 'How do you show love without using words?',
    category: Category.relationships,
    depth: 2,
  },
  f7b9pk767: {
    id: 'f7b9pk767',
    question: '¿Cuándo fue la última vez que te sentiste realmente escuchado/a?',
    translationUS: 'When was the last time you felt truly heard?',
    category: Category.relationships,
    depth: 3,
  },
  bz8pk7109: {
    id: 'bz8pk7109',
    question: 'Si pudieras arreglar una relación distanciada hoy, ¿cuál sería?',
    translationUS: 'If you could mend a distant relationship today, which one would it be?',
    category: Category.relationships,
    depth: 3,
  },
  cz9gqf942: {
    id: 'cz9gqf942',
    question: '¿Qué costumbre familiar te gustaría transmitir a las generaciones siguientes?',
    translationUS: 'What family custom would you like to pass on to the next generations?',
    category: Category.relationships,
    depth: 1,
  },
  z2kf8g829: {
    id: 'z2kf8g829',
    question: '¿Quién te hizo reír hoy? ¿De qué?',
    translationUS: 'Who made you laugh today? About what?',
    category: Category.relationships,
    depth: 1,
  },
  gk6f9q192: {
    id: 'gk6f9q192',
    question: '¿A quién de tu vida le debes un mensaje esta noche?',
    translationUS: 'Who in your life do you owe a message tonight?',
    category: Category.relationships,
    depth: 2,
  },

  // ── Educación y desarrollo personal ───────────────────────────────
  aabbcd111: {
    id: 'aabbcd111',
    question: '¿Quién fue tu maestro/a favorito? ¿Qué te enseñó que aún recuerdas?',
    translationUS: 'Who was your favorite teacher? What did they teach you that you still remember?',
    category: Category.education,
    depth: 1,
  },
  ss22Zc121: {
    id: 'ss22Zc121',
    question: '¿Cuál fue la materia que más amaste en la escuela y cuál odiaste?',
    translationUS: 'What subject did you love most in school and which one did you hate?',
    category: Category.education,
    depth: 1,
  },
  dd32aa321: {
    id: 'dd32aa321',
    question: 'Cuéntanos de algo que aprendiste fuera de la escuela y te cambió la vida.',
    translationUS: 'Tell us about something you learned outside of school that changed your life.',
    category: Category.education,
    depth: 2,
  },
  ab12aa112: {
    id: 'ab12aa112',
    question: '¿Qué cosa nueva aprendiste este mes?',
    translationUS: 'What new thing did you learn this month?',
    category: Category.education,
    depth: 1,
  },
  ba21cc212: {
    id: 'ba21cc212',
    question: '¿Qué tema podrías explicar por una hora sin aburrirte?',
    translationUS: "What topic could you talk about for an hour without getting bored?",
    category: Category.education,
    depth: 1,
  },
  aa11dc121: {
    id: 'aa11dc121',
    question: '¿Quién en esta mesa te ha enseñado algo importante? ¿Qué fue?',
    translationUS: 'Who at this table has taught you something important? What was it?',
    category: Category.education,
    depth: 2,
  },
  cc22bb221: {
    id: 'cc22bb221',
    question: '¿Qué libro, película o serie te hizo ver el mundo diferente?',
    translationUS: 'What book, movie, or show made you see the world differently?',
    category: Category.education,
    depth: 2,
  },
  dd33cc331: {
    id: 'dd33cc331',
    question: '¿Cuál fue una pregunta que te hacías de niño/a que aún no puedes responder?',
    translationUS: "What's a question you asked as a child that you still can't answer?",
    category: Category.education,
    depth: 2,
  },
  ee44dd441: {
    id: 'ee44dd441',
    question: 'Si pudieras dominar cualquier cosa en un día, ¿qué sería?',
    translationUS: 'If you could master anything in a single day, what would it be?',
    category: Category.education,
    depth: 1,
  },
  ff55ee551: {
    id: 'ff55ee551',
    question: '¿Qué creías de niño/a que ya no es verdad?',
    translationUS: "What did you believe as a child that isn't true anymore?",
    category: Category.education,
    depth: 1,
  },

  // ── Salud y bienestar físico y mental ─────────────────────────────
  aabbhc111: {
    id: 'aabbhc111',
    question: '¿Qué te hace dormir tranquilo/a?',
    translationUS: 'What helps you sleep peacefully?',
    category: Category.health,
    depth: 1,
  },
  ss42bc121: {
    id: 'ss42bc121',
    question: '¿Cuándo fue la última vez que te sentiste con mucha energía? ¿Qué estabas haciendo?',
    translationUS: 'When was the last time you felt full of energy? What were you doing?',
    category: Category.health,
    depth: 1,
  },
  qw11er121: {
    id: 'qw11er121',
    question: '¿Cuál es una comida que te hace sentir en casa?',
    translationUS: "What's a meal that makes you feel at home?",
    category: Category.health,
    depth: 1,
  },
  zc22xz121: {
    id: 'zc22xz121',
    question: '¿Cómo reconoces que estás estresado/a antes de que se te escape?',
    translationUS: "How do you notice you're stressed before it gets out of hand?",
    category: Category.health,
    depth: 2,
  },
  mn33gh121: {
    id: 'mn33gh121',
    question: '¿Qué actividad física te hace feliz, aunque sea simple?',
    translationUS: "What physical activity makes you happy, even if it's simple?",
    category: Category.health,
    depth: 1,
  },
  as44df121: {
    id: 'as44df121',
    question: '¿Quién cuida de ti cuando te enfermas? ¿Cómo lo hace?',
    translationUS: "Who takes care of you when you're sick? How do they do it?",
    category: Category.health,
    depth: 2,
  },
  gh55jk121: {
    id: 'gh55jk121',
    question: '¿Qué hábito saludable te gustaría dejar de pelear y simplemente aceptar?',
    translationUS: 'What healthy habit would you like to stop fighting and just accept?',
    category: Category.health,
    depth: 2,
  },
  ty66ui121: {
    id: 'ty66ui121',
    question: '¿Cuál fue el mejor descanso que has tenido en tu vida?',
    translationUS: "What was the best rest you've ever had in your life?",
    category: Category.health,
    depth: 1,
  },
  io77op121: {
    id: 'io77op121',
    question: '¿Qué haces cuando un día ha sido pésimo?',
    translationUS: 'What do you do when a day has been terrible?',
    category: Category.health,
    depth: 2,
  },
  qw88er121: {
    id: 'qw88er121',
    question: 'Si tuvieras que enseñarle un hábito saludable a alguien de esta mesa, ¿cuál sería?',
    translationUS: 'If you had to teach someone at this table one healthy habit, which would it be?',
    category: Category.health,
    depth: 2,
  },

  // ── Finanzas y administración del dinero ──────────────────────────
  aabbcc311: {
    id: 'aabbcc311',
    question: '¿Cuál fue la primera vez que ganaste dinero? ¿Cómo fue?',
    translationUS: 'When was the first time you earned money? How was it?',
    category: Category.money,
    depth: 1,
  },
  ss22bc122: {
    id: 'ss22bc122',
    question: '¿Qué compra te hizo más feliz en tu vida?',
    translationUS: 'What purchase made you happiest in your life?',
    category: Category.money,
    depth: 1,
  },
  jhgf1121: {
    id: 'jhgf1121',
    question: '¿Qué compra te arrepientes haber hecho?',
    translationUS: 'What purchase do you regret making?',
    category: Category.money,
    depth: 1,
  },
  poi98765: {
    id: 'poi98765',
    question: '¿Quién te enseñó sobre el dinero? ¿Qué te dijo?',
    translationUS: 'Who taught you about money? What did they tell you?',
    category: Category.money,
    depth: 2,
  },
  jhgf1233: {
    id: 'jhgf1233',
    question: 'Si te dieran una cantidad importante hoy para regalarla, ¿a quién se la darías?',
    translationUS: 'If you were given a substantial amount today to give away, who would you give it to?',
    category: Category.money,
    depth: 2,
  },
  qwerty13: {
    id: 'qwerty13',
    question: '¿Qué cosa barata te da más placer que una cara?',
    translationUS: 'What cheap thing gives you more pleasure than an expensive one?',
    category: Category.money,
    depth: 1,
  },
  asd4586: {
    id: 'asd4586',
    question: '¿Cómo te hace sentir hablar de dinero?',
    translationUS: 'How does talking about money make you feel?',
    category: Category.money,
    depth: 3,
  },
  poi90876: {
    id: 'poi90876',
    question: '¿Cuál fue el mejor regalo que recibiste que no costó dinero?',
    translationUS: "What was the best gift you received that didn't cost money?",
    category: Category.money,
    depth: 1,
  },
  jhgf1222: {
    id: 'jhgf1222',
    question: 'Si tuvieras que vivir con la mitad de lo que tienes, ¿qué soltarías primero?',
    translationUS: 'If you had to live on half of what you have, what would you give up first?',
    category: Category.money,
    depth: 2,
  },
  qwerty11: {
    id: 'qwerty11',
    question: '¿Qué sueño tienes que requiere dinero y qué estás dispuesto/a a hacer para lograrlo?',
    translationUS: 'What dream do you have that requires money, and what are you willing to do to make it happen?',
    category: Category.money,
    depth: 2,
  },

  // ── Carrera y desarrollo profesional ──────────────────────────────
  hj2wfj1: {
    id: 'hj2wfj1',
    question: '¿Cuál fue tu primer trabajo? ¿Qué aprendiste ahí?',
    translationUS: 'What was your first job? What did you learn there?',
    category: Category.work,
    depth: 1,
  },
  k1m23c1: {
    id: 'k1m23c1',
    question: '¿Quién ha sido el mejor jefe o colega que has tenido? ¿Por qué?',
    translationUS: "Who has been the best boss or colleague you've had? Why?",
    category: Category.work,
    depth: 1,
  },
  n4jksc1: {
    id: 'n4jksc1',
    question: '¿En qué parte de tu trabajo sientes que eres tú mismo/a?',
    translationUS: "What part of your work feels like it's really you?",
    category: Category.work,
    depth: 2,
  },
  m2d4s2: {
    id: 'm2d4s2',
    question: 'Si no necesitaras dinero, ¿qué harías todos los días?',
    translationUS: "If you didn't need money, what would you do every day?",
    category: Category.work,
    depth: 2,
  },
  i3lkf3: {
    id: 'i3lkf3',
    question: '¿Qué oficio o profesión admiras y nunca tuviste?',
    translationUS: 'What job or profession do you admire and never had?',
    category: Category.work,
    depth: 1,
  },
  f2d3e2: {
    id: 'f2d3e2',
    question: 'Cuéntanos de un día que saliste del trabajo sintiéndote orgulloso/a.',
    translationUS: 'Tell us about a day you left work feeling proud.',
    category: Category.work,
    depth: 2,
  },
  k1d2f1: {
    id: 'k1d2f1',
    question: '¿Qué tarea del trabajo te drena más?',
    translationUS: 'What work task drains you the most?',
    category: Category.work,
    depth: 2,
  },
  f2s3e1: {
    id: 'f2s3e1',
    question: '¿Has trabajado con alguien que cambió tu manera de ver tu carrera? ¿Quién?',
    translationUS: 'Have you worked with someone who changed how you see your career? Who?',
    category: Category.work,
    depth: 2,
  },
  e2w3f1: {
    id: 'e2w3f1',
    question: '¿Qué harías si te despidieran mañana?',
    translationUS: 'What would you do if you were let go tomorrow?',
    category: Category.work,
    depth: 3,
  },
  d2k3e1: {
    id: 'd2k3e1',
    question: '¿Cuál es un logro del trabajo que no cuelgas en la pared pero te importa?',
    translationUS: "What's a work achievement you don't hang on the wall but matters to you?",
    category: Category.work,
    depth: 3,
  },

  // ── Tecnología y su impacto en la vida cotidiana ──────────────────
  qw3hud4s: {
    id: 'qw3hud4s',
    question: '¿Cuál fue el primer aparato tecnológico que recuerdes tener?',
    translationUS: 'What was the first piece of tech you remember owning?',
    category: Category.technology,
    depth: 1,
  },
  '8fvxzc5t': {
    id: '8fvxzc5t',
    question: '¿Qué tecnología te hace la vida más fácil hoy?',
    translationUS: 'What technology makes your life easier today?',
    category: Category.technology,
    depth: 1,
  },
  '2yjhwk9u': {
    id: '2yjhwk9u',
    question: '¿Hay algo del pasado sin tecnología que extrañas?',
    translationUS: 'Is there something from a less-tech past that you miss?',
    category: Category.technology,
    depth: 1,
  },
  lft6bz8a: {
    id: 'lft6bz8a',
    question: '¿Qué te da miedo de la tecnología que viene?',
    translationUS: "What scares you about the technology that's coming?",
    category: Category.technology,
    depth: 2,
  },
  pwzskm3j: {
    id: 'pwzskm3j',
    question: 'Si tuvieras que vivir una semana sin teléfono, ¿qué harías?',
    translationUS: 'If you had to live a week without a phone, what would you do?',
    category: Category.technology,
    depth: 1,
  },
  '9xh27jd6': {
    id: '9xh27jd6',
    question: '¿Qué app o herramienta digital no podrías eliminar?',
    translationUS: "What app or digital tool couldn't you delete?",
    category: Category.technology,
    depth: 1,
  },
  wmt2r8u1: {
    id: 'wmt2r8u1',
    question: '¿Cómo eras antes de que existiera tu red social favorita?',
    translationUS: 'How were you before your favorite social network existed?',
    category: Category.technology,
    depth: 2,
  },
  zk4jdg7a: {
    id: 'zk4jdg7a',
    question: '¿Cuándo fue la última vez que la tecnología te hizo sentir cerca de alguien lejos?',
    translationUS: 'When was the last time tech made you feel close to someone far away?',
    category: Category.technology,
    depth: 2,
  },
  s6jg9mb2: {
    id: 's6jg9mb2',
    question: '¿Qué invento te gustaría ver antes de morir?',
    translationUS: 'What invention would you like to see before you die?',
    category: Category.technology,
    depth: 1,
  },
  '7xrwqf3u': {
    id: '7xrwqf3u',
    question: '¿Cómo decides cuándo apagar las pantallas?',
    translationUS: 'How do you decide when to turn off screens?',
    category: Category.technology,
    depth: 2,
  },

  // ── Actualidad y eventos mundiales ────────────────────────────────
  dssd33sss: {
    id: 'dssd33sss',
    question: '¿Qué noticia del último año te marcó? ¿Por qué?',
    translationUS: 'What news story from the last year stuck with you? Why?',
    category: Category.news,
    depth: 2,
  },
  aabb2233d: {
    id: 'aabb2233d',
    question: '¿Cómo eliges qué noticias leer e ignorar?',
    translationUS: 'How do you decide which news to read and which to ignore?',
    category: Category.news,
    depth: 1,
  },
  ccddee124: {
    id: 'ccddee124',
    question: '¿Hay algo que está pasando en el mundo que te da esperanza?',
    translationUS: 'Is there anything happening in the world that gives you hope?',
    category: Category.news,
    depth: 2,
  },
  bbeessd11: {
    id: 'bbeessd11',
    question: '¿Cuál fue un evento histórico que viviste en directo? ¿Dónde estabas?',
    translationUS: 'What historical event did you live through? Where were you?',
    category: Category.news,
    depth: 1,
  },
  ffgg2233a: {
    id: 'ffgg2233a',
    question: 'Si pudieras cambiar una sola cosa del mundo hoy, ¿qué sería?',
    translationUS: 'If you could change just one thing in the world today, what would it be?',
    category: Category.news,
    depth: 2,
  },
  ccddee123: {
    id: 'ccddee123',
    question: '¿Qué noticia te hizo cambiar de opinión sobre algo?',
    translationUS: 'What news story made you change your mind about something?',
    category: Category.news,
    depth: 2,
  },
  aabblle11: {
    id: 'aabblle11',
    question: '¿Cómo te enteras de lo que pasa en el mundo? ¿Confías en esa fuente?',
    translationUS: "How do you learn what's happening in the world? Do you trust that source?",
    category: Category.news,
    depth: 1,
  },
  kkjjcc122: {
    id: 'kkjjcc122',
    question: '¿Qué historia inspiradora conoces que casi nadie sabe?',
    translationUS: 'What inspiring story do you know that almost no one knows?',
    category: Category.news,
    depth: 2,
  },
  bbddaatt1: {
    id: 'bbddaatt1',
    question: '¿Hay alguna causa por la que marcharías?',
    translationUS: 'Is there a cause you would march for?',
    category: Category.news,
    depth: 3,
  },
  aaeeffgg1: {
    id: 'aaeeffgg1',
    question: 'Si tuvieras cinco minutos en un noticiero, ¿qué dirías?',
    translationUS: 'If you had five minutes on the evening news, what would you say?',
    category: Category.news,
    depth: 2,
  },

  // ── Comunidad y responsabilidad social ────────────────────────────
  fhg45klj: {
    id: 'fhg45klj',
    question: '¿Quién es un vecino que recuerdas con cariño? ¿Por qué?',
    translationUS: 'Who is a neighbor you remember fondly? Why?',
    category: Category.community,
    depth: 1,
  },
  pq567983: {
    id: 'pq567983',
    question: '¿Cuándo ayudaste a un desconocido por última vez? ¿Cómo te sentiste?',
    translationUS: 'When was the last time you helped a stranger? How did it feel?',
    category: Category.community,
    depth: 2,
  },
  lmn456op: {
    id: 'lmn456op',
    question: '¿Qué persona de tu barrio o pueblo te ha ayudado de forma especial?',
    translationUS: 'Who in your neighborhood or town has helped you in a special way?',
    category: Category.community,
    depth: 2,
  },
  qwertyu1: {
    id: 'qwertyu1',
    question: '¿Qué tradición o celebración de tu comunidad más disfrutas?',
    translationUS: 'What tradition or celebration in your community do you enjoy most?',
    category: Category.community,
    depth: 1,
  },
  asdfghj2: {
    id: 'asdfghj2',
    question: 'Si pudieras organizar un evento para tu barrio, ¿qué sería?',
    translationUS: 'If you could organize an event for your neighborhood, what would it be?',
    category: Category.community,
    depth: 1,
  },
  zxcvbnm3: {
    id: 'zxcvbnm3',
    question: '¿Cuál es un problema de tu comunidad que te gustaría resolver?',
    translationUS: "What's a problem in your community you'd like to solve?",
    category: Category.community,
    depth: 2,
  },
  poiuyt12: {
    id: 'poiuyt12',
    question: '¿A quién le pedirías ayuda en una emergencia que no sea de tu familia?',
    translationUS: "Who would you ask for help in an emergency if it wasn't family?",
    category: Category.community,
    depth: 2,
  },
  lkjhgf34: {
    id: 'lkjhgf34',
    question: '¿Cómo conoces a tus vecinos? ¿Te gustaría conocerlos más?',
    translationUS: 'How do you know your neighbors? Would you like to know them more?',
    category: Category.community,
    depth: 1,
  },
  mnbvcxz5: {
    id: 'mnbvcxz5',
    question: '¿Qué aprendiste de alguien mayor de tu comunidad?',
    translationUS: 'What have you learned from an older person in your community?',
    category: Category.community,
    depth: 2,
  },
  yuiop987: {
    id: 'yuiop987',
    question: '¿Qué haces que mejora la vida de alguien a tu alrededor?',
    translationUS: 'What do you do that improves the life of someone around you?',
    category: Category.community,
    depth: 2,
  },

  // ── Medio ambiente y sustentabilidad ──────────────────────────────
  aabbcc11s: {
    id: 'aabbcc11s',
    question: '¿Cuál es el lugar natural más hermoso donde has estado?',
    translationUS: "What is the most beautiful natural place you've ever been?",
    category: Category.environments,
    depth: 1,
  },
  ss22bc141: {
    id: 'ss22bc141',
    question: '¿Qué animal o planta te fascina? ¿Por qué?',
    translationUS: 'What animal or plant fascinates you? Why?',
    category: Category.environments,
    depth: 1,
  },
  asd34hf12: {
    id: 'asd34hf12',
    question: '¿Qué hábito ecológico has incorporado a tu vida?',
    translationUS: 'What eco-friendly habit have you added to your life?',
    category: Category.environments,
    depth: 1,
  },
  hjk08dk21: {
    id: 'hjk08dk21',
    question: 'Cuéntanos de un momento al aire libre que te haya calmado.',
    translationUS: 'Tell us about an outdoor moment that calmed you.',
    category: Category.environments,
    depth: 2,
  },
  sdj12ke92: {
    id: 'sdj12ke92',
    question: '¿Qué te gustaría enseñarles a los más chicos sobre la naturaleza?',
    translationUS: 'What would you like to teach the younger ones about nature?',
    category: Category.environments,
    depth: 2,
  },
  das12bn21: {
    id: 'das12bn21',
    question: 'Si tuvieras que plantar un árbol, ¿dónde lo plantarías y por qué?',
    translationUS: 'If you had to plant a tree, where would you plant it and why?',
    category: Category.environments,
    depth: 1,
  },
  fhg56jm22: {
    id: 'fhg56jm22',
    question: '¿Qué lugar natural te duele ver deteriorarse?',
    translationUS: 'What natural place hurts you to see deteriorating?',
    category: Category.environments,
    depth: 3,
  },
  gfh09lm10: {
    id: 'gfh09lm10',
    question: '¿Cuándo fue la primera vez que te conectaste con la naturaleza?',
    translationUS: 'When was the first time you felt connected to nature?',
    category: Category.environments,
    depth: 2,
  },
  hjy75ls21: {
    id: 'hjy75ls21',
    question: 'Si el planeta tuviera voz, ¿qué te diría?',
    translationUS: 'If the planet had a voice, what would it say to you?',
    category: Category.environments,
    depth: 2,
  },
  sdk09ls92: {
    id: 'sdk09ls92',
    question: '¿Qué podrías dejar de comprar por el planeta?',
    translationUS: 'What could you stop buying for the sake of the planet?',
    category: Category.environments,
    depth: 2,
  },

  // ── Cultura y diversidad ──────────────────────────────────────────
  mjb4dz00: {
    id: 'mjb4dz00',
    question: '¿Qué plato de tu cultura sigue siendo tu favorito?',
    translationUS: 'What dish from your culture is still your favorite?',
    category: Category.culture,
    depth: 1,
  },
  h9j8i1k2: {
    id: 'h9j8i1k2',
    question: '¿Qué tradición de tu familia no querrías perder?',
    translationUS: 'What family tradition would you never want to lose?',
    category: Category.culture,
    depth: 2,
  },
  c7jd97y1: {
    id: 'c7jd97y1',
    question: '¿Qué canción siempre te lleva a un momento específico?',
    translationUS: 'What song always takes you back to a specific moment?',
    category: Category.culture,
    depth: 1,
  },
  r37kf2l6: {
    id: 'r37kf2l6',
    question: '¿Qué has aprendido de una cultura distinta a la tuya?',
    translationUS: 'What have you learned from a culture different from yours?',
    category: Category.culture,
    depth: 2,
  },
  e8d4g7m4: {
    id: 'e8d4g7m4',
    question: '¿Cuándo fue una ocasión en que te sentiste orgulloso/a de tus raíces?',
    translationUS: 'When was a time you felt proud of your roots?',
    category: Category.culture,
    depth: 2,
  },
  w2f3q0i7: {
    id: 'w2f3q0i7',
    question: '¿Qué celebración familiar es tu favorita? ¿Por qué?',
    translationUS: 'What family celebration is your favorite? Why?',
    category: Category.culture,
    depth: 1,
  },
  f4k7d0x2: {
    id: 'f4k7d0x2',
    question: '¿Qué palabra o frase en tu idioma te encanta y es difícil de traducir?',
    translationUS: "What word or phrase in your language do you love that's hard to translate?",
    category: Category.culture,
    depth: 1,
  },
  s1j2c6h3: {
    id: 's1j2c6h3',
    question: '¿Quién en tu familia guarda las historias?',
    translationUS: 'Who in your family keeps the stories?',
    category: Category.culture,
    depth: 2,
  },
  m9p3l1q3: {
    id: 'm9p3l1q3',
    question: '¿Qué parte de otra cultura te gustaría adoptar?',
    translationUS: 'What part of another culture would you like to adopt?',
    category: Category.culture,
    depth: 1,
  },
  k2x1g7z8: {
    id: 'k2x1g7z8',
    question: '¿Cuál es el viaje, real o imaginario, que más ha cambiado tu forma de ver el mundo?',
    translationUS: 'What trip, real or imagined, has most changed how you see the world?',
    category: Category.culture,
    depth: 3,
  },

  // ── Espiritualidad y fe ───────────────────────────────────────────
  fdh123ghf: {
    id: 'fdh123ghf',
    question: '¿Qué te llena de gratitud hoy?',
    translationUS: 'What fills you with gratitude today?',
    category: Category.spirituality,
    depth: 1,
  },
  fhg321hjf: {
    id: 'fhg321hjf',
    question: '¿Cómo perdonas? ¿Hay alguien a quien tienes que perdonar ahora?',
    translationUS: 'How do you forgive? Is there someone you need to forgive right now?',
    category: Category.spirituality,
    depth: 3,
  },
  kjh231fhg: {
    id: 'kjh231fhg',
    question: '¿Qué le da sentido a tu vida?',
    translationUS: 'What gives meaning to your life?',
    category: Category.spirituality,
    depth: 3,
  },
  jhg123fhg: {
    id: 'jhg123fhg',
    question: 'Cuéntanos de un momento en que te sentiste parte de algo más grande que tú.',
    translationUS: 'Tell us about a moment you felt part of something bigger than yourself.',
    category: Category.spirituality,
    depth: 3,
  },
  fgh123fjh: {
    id: 'fgh123fjh',
    question: '¿Qué creencia has cambiado en tu vida?',
    translationUS: 'What belief have you changed in your life?',
    category: Category.spirituality,
    depth: 3,
  },
  hjg213ghf: {
    id: 'hjg213ghf',
    question: '¿Cómo encuentras paz cuando el mundo va muy rápido?',
    translationUS: 'How do you find peace when the world moves too fast?',
    category: Category.spirituality,
    depth: 2,
  },
  fgh123fhg: {
    id: 'fgh123fhg',
    question: '¿A quién te gustaría agradecer que ya no está? ¿Qué le dirías?',
    translationUS: 'Who would you like to thank who is no longer here? What would you tell them?',
    category: Category.spirituality,
    depth: 3,
  },
  fhg123hjf: {
    id: 'fhg123hjf',
    question: '¿Qué haces cuando te sientes perdido/a?',
    translationUS: 'What do you do when you feel lost?',
    category: Category.spirituality,
    depth: 2,
  },
  fgh123jhg: {
    id: 'fgh123jhg',
    question: 'Si pudieras hablar con tu yo de 80 años, ¿qué le preguntarías?',
    translationUS: 'If you could speak with your 80-year-old self, what would you ask them?',
    category: Category.spirituality,
    depth: 2,
  },
  fgh123hjg: {
    id: 'fgh123hjg',
    question: '¿Qué te gustaría que la gente recuerde de ti?',
    translationUS: 'What would you like people to remember about you?',
    category: Category.spirituality,
    depth: 3,
  },

  // ── Planificación y organización del tiempo libre ────────────────
  sdfs9s90s: {
    id: 'sdfs9s90s',
    question: '¿Cuál es tu domingo ideal?',
    translationUS: 'What does your ideal Sunday look like?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs98s90: {
    id: 'sdfs98s90',
    question: '¿Qué hobby tenías de niño/a que ya no haces y extrañas?',
    translationUS: 'What hobby did you have as a child that you no longer do and miss?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s99s: {
    id: 'sdfs9s99s',
    question: 'Si tuvieras un día libre mañana sin responsabilidades, ¿qué harías?',
    translationUS: 'If you had a free day tomorrow with no responsibilities, what would you do?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90x: {
    id: 'sdfs9s90x',
    question: '¿Qué actividad te hace perder la noción del tiempo?',
    translationUS: 'What activity makes you lose track of time?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90w: {
    id: 'sdfs9s90w',
    question: '¿Qué te gusta hacer solo/a que no harías con nadie más?',
    translationUS: "What do you like to do alone that you wouldn't do with anyone else?",
    category: Category.freeTime,
    depth: 2,
  },
  sdfs9s90n: {
    id: 'sdfs9s90n',
    question: '¿Cuál fue la mejor vacación de tu vida?',
    translationUS: 'What was the best vacation of your life?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90m: {
    id: 'sdfs9s90m',
    question: '¿Qué pasatiempo de alguien más te gustaría probar?',
    translationUS: 'What hobby of someone else would you like to try?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90o: {
    id: 'sdfs9s90o',
    question: 'Si tu familia te regalara un día a tu gusto, ¿qué pedirías?',
    translationUS: 'If your family gifted you a day entirely your way, what would you ask for?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90p: {
    id: 'sdfs9s90p',
    question: '¿Cuándo fue la última vez que jugaste? ¿A qué?',
    translationUS: 'When was the last time you played? What did you play?',
    category: Category.freeTime,
    depth: 1,
  },
  sdfs9s90q: {
    id: 'sdfs9s90q',
    question: '¿Qué harías si tuvieras todo un sábado solo para ti en tu ciudad?',
    translationUS: 'What would you do if you had a whole Saturday to yourself in your city?',
    category: Category.freeTime,
    depth: 1,
  },

  // ── Historias familiares (Duke & Fivush "Do You Know?" scale) ──────
  //
  // Research shows children who know their family history score higher
  // on self-esteem, resilience, and family functioning (Duke, Lazarus &
  // Fivush, 2008). These questions build the "intergenerational self".
  fam_story_01: {
    id: 'fam_story_01',
    question: '¿Sabes cómo se conocieron tus padres o abuelos? Cuéntanos la historia.',
    translationUS: 'Do you know how your parents or grandparents met? Tell us the story.',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_02: {
    id: 'fam_story_02',
    question: '¿Sabes de dónde viene tu nombre? ¿Quién lo eligió y por qué?',
    translationUS: 'Do you know where your name comes from? Who chose it and why?',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_03: {
    id: 'fam_story_03',
    question: '¿Conoces una historia difícil que tu familia logró superar?',
    translationUS: 'Do you know a hard story your family managed to overcome?',
    category: Category.familyStories,
    depth: 3,
  },
  fam_story_04: {
    id: 'fam_story_04',
    question: '¿Sabes dónde crecieron tus abuelos? ¿Cómo era ese lugar?',
    translationUS: 'Do you know where your grandparents grew up? What was that place like?',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_05: {
    id: 'fam_story_05',
    question: '¿A qué miembro de la familia dicen que te pareces más? ¿Estás de acuerdo?',
    translationUS: 'Which family member do people say you resemble most? Do you agree?',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_06: {
    id: 'fam_story_06',
    question: '¿Sabes qué trabajo tenían tus abuelos o bisabuelos cuando eran jóvenes?',
    translationUS: 'Do you know what jobs your grandparents or great-grandparents had when they were young?',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_07: {
    id: 'fam_story_07',
    question: '¿Conoces alguna anécdota graciosa de tus padres cuando eran niños?',
    translationUS: 'Do you know a funny story about your parents when they were kids?',
    category: Category.familyStories,
    depth: 1,
  },
  fam_story_08: {
    id: 'fam_story_08',
    question: '¿Hay algún objeto en tu casa que tenga una historia familiar detrás? ¿Cuál es?',
    translationUS: 'Is there an object in your home that has a family story behind it? What is it?',
    category: Category.familyStories,
    depth: 2,
  },
  fam_story_09: {
    id: 'fam_story_09',
    question: '¿Cuál es la tradición más antigua de tu familia que aún se mantiene?',
    translationUS: 'What is the oldest tradition in your family that still continues?',
    category: Category.familyStories,
    depth: 2,
  },
  fam_story_10: {
    id: 'fam_story_10',
    question: 'Si pudieras hacerle una pregunta a un antepasado, ¿a quién elegirías y qué le preguntarías?',
    translationUS: 'If you could ask an ancestor one question, who would you choose and what would you ask?',
    category: Category.familyStories,
    depth: 3,
  },

  // ── Trivia · Países ──────────────────────────────────────────────
  trivia_country_01: { id: 'trivia_country_01', question: '¿Cuál es la capital de Australia?', translationUS: 'What is the capital of Australia?', category: Category.triviaCountries, answer: 'Canberra', answerUS: 'Canberra' },
  trivia_country_02: { id: 'trivia_country_02', question: '¿En qué continente está Egipto?', translationUS: 'What continent is Egypt in?', category: Category.triviaCountries, answer: 'África', answerUS: 'Africa' },
  trivia_country_03: { id: 'trivia_country_03', question: '¿Cuál es el país más grande del mundo en territorio?', translationUS: "What is the world's largest country by area?", category: Category.triviaCountries, answer: 'Rusia', answerUS: 'Russia' },
  trivia_country_04: { id: 'trivia_country_04', question: '¿Qué país tiene forma de bota?', translationUS: 'Which country is shaped like a boot?', category: Category.triviaCountries, answer: 'Italia', answerUS: 'Italy' },
  trivia_country_05: { id: 'trivia_country_05', question: '¿Cuál es la capital de Japón?', translationUS: 'What is the capital of Japan?', category: Category.triviaCountries, answer: 'Tokio', answerUS: 'Tokyo' },
  trivia_country_06: { id: 'trivia_country_06', question: '¿En qué país está la Torre Eiffel?', translationUS: 'In which country is the Eiffel Tower?', category: Category.triviaCountries, answer: 'Francia', answerUS: 'France' },
  trivia_country_07: { id: 'trivia_country_07', question: '¿Qué idioma se habla oficialmente en Brasil?', translationUS: "What's the official language of Brazil?", category: Category.triviaCountries, answer: 'Portugués', answerUS: 'Portuguese' },
  trivia_country_08: { id: 'trivia_country_08', question: '¿Cuál es la capital de Argentina?', translationUS: 'What is the capital of Argentina?', category: Category.triviaCountries, answer: 'Buenos Aires', answerUS: 'Buenos Aires' },
  trivia_country_09: { id: 'trivia_country_09', question: '¿Qué océano separa América de Europa?', translationUS: 'Which ocean separates America from Europe?', category: Category.triviaCountries, answer: 'Atlántico', answerUS: 'Atlantic' },
  trivia_country_10: { id: 'trivia_country_10', question: '¿Cuál es el país más pequeño del mundo?', translationUS: "What is the world's smallest country?", category: Category.triviaCountries, answer: 'Vaticano', answerUS: 'Vatican City' },

  // ── Trivia · Ciudades ────────────────────────────────────────────
  trivia_city_01: { id: 'trivia_city_01', question: '¿En qué ciudad está la Estatua de la Libertad?', translationUS: 'In which city is the Statue of Liberty?', category: Category.triviaCities, answer: 'Nueva York', answerUS: 'New York' },
  trivia_city_02: { id: 'trivia_city_02', question: '¿En qué ciudad está el Coliseo Romano?', translationUS: 'In which city is the Roman Colosseum?', category: Category.triviaCities, answer: 'Roma', answerUS: 'Rome' },
  trivia_city_03: { id: 'trivia_city_03', question: '¿Cuál es la capital de España?', translationUS: 'What is the capital of Spain?', category: Category.triviaCities, answer: 'Madrid', answerUS: 'Madrid' },
  trivia_city_04: { id: 'trivia_city_04', question: '¿En qué ciudad está la Sagrada Familia?', translationUS: 'In which city is the Sagrada Familia?', category: Category.triviaCities, answer: 'Barcelona', answerUS: 'Barcelona' },
  trivia_city_05: { id: 'trivia_city_05', question: '¿Cuál es la capital de México?', translationUS: 'What is the capital of Mexico?', category: Category.triviaCities, answer: 'Ciudad de México', answerUS: 'Mexico City' },
  trivia_city_06: { id: 'trivia_city_06', question: '¿En qué ciudad nacieron los Beatles?', translationUS: 'In which city were the Beatles born?', category: Category.triviaCities, answer: 'Liverpool', answerUS: 'Liverpool' },
  trivia_city_07: { id: 'trivia_city_07', question: '¿Cuál es la capital de Colombia?', translationUS: 'What is the capital of Colombia?', category: Category.triviaCities, answer: 'Bogotá', answerUS: 'Bogotá' },
  trivia_city_08: { id: 'trivia_city_08', question: '¿En qué ciudad está la Torre de Pisa?', translationUS: 'In which city is the Leaning Tower?', category: Category.triviaCities, answer: 'Pisa', answerUS: 'Pisa' },
  trivia_city_09: { id: 'trivia_city_09', question: '¿Cuál es la capital de Ecuador?', translationUS: 'What is the capital of Ecuador?', category: Category.triviaCities, answer: 'Quito', answerUS: 'Quito' },
  trivia_city_10: { id: 'trivia_city_10', question: '¿En qué ciudad está el Cristo Redentor?', translationUS: 'In which city is the Christ the Redeemer statue?', category: Category.triviaCities, answer: 'Río de Janeiro', answerUS: 'Rio de Janeiro' },

  // ── Trivia · Música ──────────────────────────────────────────────
  trivia_music_01: { id: 'trivia_music_01', question: '¿Quién compuso "Las cuatro estaciones"?', translationUS: 'Who composed "The Four Seasons"?', category: Category.triviaMusic, answer: 'Antonio Vivaldi', answerUS: 'Antonio Vivaldi' },
  trivia_music_02: { id: 'trivia_music_02', question: '¿De qué banda era John Lennon?', translationUS: 'Which band was John Lennon part of?', category: Category.triviaMusic, answer: 'The Beatles', answerUS: 'The Beatles' },
  trivia_music_03: { id: 'trivia_music_03', question: '¿Cuántas cuerdas tiene una guitarra estándar?', translationUS: 'How many strings does a standard guitar have?', category: Category.triviaMusic, answer: '6', answerUS: '6' },
  trivia_music_04: { id: 'trivia_music_04', question: '¿Quién canta "Despacito"?', translationUS: 'Who sings "Despacito"?', category: Category.triviaMusic, answer: 'Luis Fonsi (con Daddy Yankee)', answerUS: 'Luis Fonsi (feat. Daddy Yankee)' },
  trivia_music_05: { id: 'trivia_music_05', question: '¿Quién compuso la Novena Sinfonía?', translationUS: 'Who composed the Ninth Symphony?', category: Category.triviaMusic, answer: 'Ludwig van Beethoven', answerUS: 'Ludwig van Beethoven' },
  trivia_music_06: { id: 'trivia_music_06', question: '¿Quién es conocida como la "Reina del Pop"?', translationUS: 'Who is known as the "Queen of Pop"?', category: Category.triviaMusic, answer: 'Madonna', answerUS: 'Madonna' },
  trivia_music_07: { id: 'trivia_music_07', question: '¿Cuántas notas musicales hay en la escala básica?', translationUS: 'How many notes are there in the basic musical scale?', category: Category.triviaMusic, answer: '7', answerUS: '7' },
  trivia_music_08: { id: 'trivia_music_08', question: '¿Qué género musical hace famoso a Bad Bunny?', translationUS: 'What genre made Bad Bunny famous?', category: Category.triviaMusic, answer: 'Reggaetón', answerUS: 'Reggaeton' },
  trivia_music_09: { id: 'trivia_music_09', question: '¿Qué instrumento toca un pianista?', translationUS: 'What instrument does a pianist play?', category: Category.triviaMusic, answer: 'Piano', answerUS: 'Piano' },
  trivia_music_10: { id: 'trivia_music_10', question: '¿Quién es el "Rey del Pop"?', translationUS: 'Who is the "King of Pop"?', category: Category.triviaMusic, answer: 'Michael Jackson', answerUS: 'Michael Jackson' },

  // ── Trivia · Frutas ──────────────────────────────────────────────
  trivia_fruit_01: { id: 'trivia_fruit_01', question: '¿Qué fruta es famosa por su alto contenido de vitamina C?', translationUS: 'Which fruit is famous for its high vitamin C?', category: Category.triviaFruits, answer: 'Naranja (también limón, kiwi, guayaba)', answerUS: 'Orange (also lemon, kiwi, guava)' },
  trivia_fruit_02: { id: 'trivia_fruit_02', question: '¿Qué fruta amarilla y curvada comen los monos en los dibujos?', translationUS: 'What yellow curved fruit do cartoon monkeys eat?', category: Category.triviaFruits, answer: 'Plátano', answerUS: 'Banana' },
  trivia_fruit_03: { id: 'trivia_fruit_03', question: '¿Qué fruta tiene sus semillas por fuera?', translationUS: 'Which fruit has its seeds on the outside?', category: Category.triviaFruits, answer: 'Fresa', answerUS: 'Strawberry' },
  trivia_fruit_04: { id: 'trivia_fruit_04', question: '¿Qué fruta es verde por fuera y roja por dentro?', translationUS: 'Which fruit is green outside and red inside?', category: Category.triviaFruits, answer: 'Sandía', answerUS: 'Watermelon' },
  trivia_fruit_05: { id: 'trivia_fruit_05', question: '¿Con qué fruta se hace el vino?', translationUS: 'What fruit is wine made from?', category: Category.triviaFruits, answer: 'Uva', answerUS: 'Grape' },
  trivia_fruit_06: { id: 'trivia_fruit_06', question: '¿Qué fruta está cubierta de pelos finos y es marrón por fuera?', translationUS: 'Which fruit is covered in fuzzy hair and brown on the outside?', category: Category.triviaFruits, answer: 'Kiwi', answerUS: 'Kiwi' },
  trivia_fruit_07: { id: 'trivia_fruit_07', question: '¿Qué fruta tropical tiene una corona de hojas?', translationUS: 'Which tropical fruit has a crown of leaves on top?', category: Category.triviaFruits, answer: 'Piña', answerUS: 'Pineapple' },
  trivia_fruit_08: { id: 'trivia_fruit_08', question: '¿Qué fruta roja con tallo verde tiene un solo hueso por dentro?', translationUS: 'Which red fruit with a green stem has one pit inside?', category: Category.triviaFruits, answer: 'Cereza', answerUS: 'Cherry' },
  trivia_fruit_09: { id: 'trivia_fruit_09', question: '¿Qué fruta morada parecida a la uva se usa para hacer mermelada?', translationUS: 'Which purple grape-like fruit is often made into jam?', category: Category.triviaFruits, answer: 'Mora', answerUS: 'Blackberry' },
  trivia_fruit_10: { id: 'trivia_fruit_10', question: '¿Qué fruta amarilla y ácida se exprime para limonada?', translationUS: 'Which sour yellow fruit is squeezed for lemonade?', category: Category.triviaFruits, answer: 'Limón', answerUS: 'Lemon' },

  // ── Trivia · Fútbol ──────────────────────────────────────────────
  trivia_football_01: { id: 'trivia_football_01', question: '¿Cuántos jugadores tiene un equipo de fútbol en la cancha?', translationUS: 'How many players does a soccer team have on the field?', category: Category.triviaFootball, answer: '11', answerUS: '11' },
  trivia_football_02: { id: 'trivia_football_02', question: '¿Qué país ganó el Mundial 2022?', translationUS: 'Which country won the 2022 World Cup?', category: Category.triviaFootball, answer: 'Argentina', answerUS: 'Argentina' },
  trivia_football_03: { id: 'trivia_football_03', question: '¿De qué país es Lionel Messi?', translationUS: 'What country is Lionel Messi from?', category: Category.triviaFootball, answer: 'Argentina', answerUS: 'Argentina' },
  trivia_football_04: { id: 'trivia_football_04', question: '¿Cuántos minutos dura un partido de fútbol estándar?', translationUS: 'How many minutes does a standard soccer match last?', category: Category.triviaFootball, answer: '90', answerUS: '90' },
  trivia_football_05: { id: 'trivia_football_05', question: '¿En qué país nació el fútbol moderno?', translationUS: 'In which country was modern soccer born?', category: Category.triviaFootball, answer: 'Inglaterra', answerUS: 'England' },
  trivia_football_06: { id: 'trivia_football_06', question: '¿De qué país es Cristiano Ronaldo?', translationUS: 'What country is Cristiano Ronaldo from?', category: Category.triviaFootball, answer: 'Portugal', answerUS: 'Portugal' },
  trivia_football_07: { id: 'trivia_football_07', question: '¿De qué color es la tarjeta que expulsa a un jugador?', translationUS: 'What color is the card that sends a player off?', category: Category.triviaFootball, answer: 'Roja', answerUS: 'Red' },
  trivia_football_08: { id: 'trivia_football_08', question: '¿Cada cuántos años se juega el Mundial de Fútbol?', translationUS: 'How often is the World Cup held?', category: Category.triviaFootball, answer: 'Cada 4 años', answerUS: 'Every 4 years' },
  trivia_football_09: { id: 'trivia_football_09', question: '¿Cuántos puntos suma una victoria en un torneo?', translationUS: 'How many points does a win count in a league?', category: Category.triviaFootball, answer: '3', answerUS: '3' },
  trivia_football_10: { id: 'trivia_football_10', question: '¿Qué jugador es apodado "La Pulga"?', translationUS: 'Which player is nicknamed "The Flea"?', category: Category.triviaFootball, answer: 'Lionel Messi', answerUS: 'Lionel Messi' },

  // ── Trivia · Colores ─────────────────────────────────────────────
  trivia_color_01: { id: 'trivia_color_01', question: '¿Qué color resulta de mezclar amarillo y azul?', translationUS: 'What color do you get mixing yellow and blue?', category: Category.triviaColors, answer: 'Verde', answerUS: 'Green' },
  trivia_color_02: { id: 'trivia_color_02', question: '¿De qué color es el cielo en un día despejado?', translationUS: 'What color is the sky on a clear day?', category: Category.triviaColors, answer: 'Azul', answerUS: 'Blue' },
  trivia_color_03: { id: 'trivia_color_03', question: '¿Qué dos colores forman el púrpura?', translationUS: 'Which two colors make purple?', category: Category.triviaColors, answer: 'Rojo y azul', answerUS: 'Red and blue' },
  trivia_color_04: { id: 'trivia_color_04', question: '¿Cuántos colores tiene el arcoíris?', translationUS: 'How many colors does the rainbow have?', category: Category.triviaColors, answer: '7', answerUS: '7' },
  trivia_color_05: { id: 'trivia_color_05', question: '¿Qué color se obtiene al mezclar rojo y amarillo?', translationUS: 'What color do you get mixing red and yellow?', category: Category.triviaColors, answer: 'Naranja', answerUS: 'Orange' },
  trivia_color_06: { id: 'trivia_color_06', question: '¿Cuáles son los tres colores primarios?', translationUS: 'What are the three primary colors?', category: Category.triviaColors, answer: 'Rojo, azul y amarillo', answerUS: 'Red, blue and yellow' },
  trivia_color_07: { id: 'trivia_color_07', question: '¿Qué color es complementario del rojo?', translationUS: 'What color is complementary to red?', category: Category.triviaColors, answer: 'Verde', answerUS: 'Green' },
  trivia_color_08: { id: 'trivia_color_08', question: '¿De qué color es la nieve?', translationUS: 'What color is snow?', category: Category.triviaColors, answer: 'Blanco', answerUS: 'White' },
  trivia_color_09: { id: 'trivia_color_09', question: '¿Qué color tiene el sol en los dibujos infantiles?', translationUS: "What color is the sun in children's drawings?", category: Category.triviaColors, answer: 'Amarillo', answerUS: 'Yellow' },
  trivia_color_10: { id: 'trivia_color_10', question: '¿De qué color es el césped sano?', translationUS: 'What color is healthy grass?', category: Category.triviaColors, answer: 'Verde', answerUS: 'Green' },
};

// ── Appreciation prompts (Gottman fondness & admiration system) ──────
//
// Injected every 4-5 normal questions during gameplay. Not part of the
// regular question pool — they're a separate mechanic designed to build
// gratitude and explicit positive regard among family members.
export interface AppreciationPrompt {
  id: string;
  prompt: string;
  translationUS: string;
}

export const appreciationPrompts: AppreciationPrompt[] = [
  {
    id: 'appr_01',
    prompt: 'Dile a alguien de esta mesa algo que admiras de él/ella.',
    translationUS: 'Tell someone at this table something you admire about them.',
  },
  {
    id: 'appr_02',
    prompt: 'Agradece a alguien aquí por algo que hizo por ti esta semana.',
    translationUS: 'Thank someone here for something they did for you this week.',
  },
  {
    id: 'appr_03',
    prompt: '¿Cuál es tu recuerdo favorito con alguien que está aquí?',
    translationUS: 'What is your favorite memory with someone who is here?',
  },
  {
    id: 'appr_04',
    prompt: 'Dile a alguien de esta mesa por qué te gusta pasar tiempo con él/ella.',
    translationUS: 'Tell someone at this table why you enjoy spending time with them.',
  },
  {
    id: 'appr_05',
    prompt: '¿Quién de esta mesa te hizo sonreír recientemente? Cuéntale.',
    translationUS: 'Who at this table made you smile recently? Tell them.',
  },
  {
    id: 'appr_06',
    prompt: 'Dile a alguien aquí algo que aprendiste de él/ella.',
    translationUS: 'Tell someone here something you learned from them.',
  },
  {
    id: 'appr_07',
    prompt: 'Mira a alguien de la mesa y dile qué te hace sentir seguro/a de él/ella.',
    translationUS: 'Look at someone at the table and tell them what makes you feel safe around them.',
  },
  {
    id: 'appr_08',
    prompt: '¿A quién de esta mesa le darías un premio? ¿Por qué?',
    translationUS: 'Who at this table would you give an award to? Why?',
  },
];
