export interface Question {
  id: string;
  question: string;
  translationUS: string;
  category: Category;
}

export enum Category {
  random = 'Aleatorio',
  goals = 'Metas y sueños personales',
  principles = 'Valores y principios importantes',
  challenges = 'Cambios y desafíos en la vida personal',
  relationships = 'Comunicación y relaciones interpersonales',
  education = 'Educación y desarrollo personal',
  health = 'Salud y bienestar físico y mental',
  money = 'Finanzas y administración del dinero',
  work = 'Carrera y desarrollo profesional',
  technology = 'Tecnología y su impacto en la vida cotidiana',
  news = 'Actualidad y eventos mundiales',
  community = 'Comunidad y responsabilidad social',
  environments = 'Medio ambiente y sustentabilidad',
  culture = 'Cultura y diversidad',
  spirituality = 'Espiritualidad y fe',
  freeTime = 'Planificación y organización del tiempo libre.',
}

export const defaultCategory = {
  [Category.random]: {
    name: Category.random,
    image: '/assets/categories/random.png',
  },
  [Category.goals]: {
    name: Category.goals,
    image: '/assets/categories/goals.png',
  },
  [Category.principles]: {
    name: Category.principles,
    image: '/assets/categories/principles.png',
  },
  [Category.challenges]: {
    name: Category.challenges,
    image: '/assets/categories/challenges.png',
  },
  [Category.relationships]: {
    name: Category.relationships,
    image: '/assets/categories/relationships.png',
  },
  [Category.education]: {
    name: Category.education,
    image: '/assets/categories/education.png',
  },
  [Category.health]: {
    name: Category.health,
    image: '/assets/categories/health.png',
  },
  [Category.money]: {
    name: Category.money,
    image: '/assets/categories/money.png',
  },
  [Category.work]: {
    name: Category.work,
    image: '/assets/categories/work.png',
  },
  [Category.technology]: {
    name: Category.technology,
    image: '/assets/categories/technology.png',
  },
  [Category.news]: {
    name: Category.news,
    image: '/assets/categories/news.png',
  },
  [Category.community]: {
    name: Category.community,
    image: '/assets/categories/community.png',
  },
  [Category.environments]: {
    name: Category.environments,
    image: '/assets/categories/environments.png',
  },
  [Category.culture]: {
    name: Category.culture,
    image: '/assets/categories/culture.png',
  },
  [Category.spirituality]: {
    name: Category.spirituality,
    image: '/assets/categories/spirituality.png',
  },
  [Category.freeTime]: {
    name: Category.freeTime,
    image: '/assets/categories/freeTime.png',
  },
};

export const defaultQuestionCounter = {
  [Category.random]: 0,
  [Category.goals]: 0,
  [Category.principles]: 0,
  [Category.challenges]: 0,
  [Category.relationships]: 0,
  [Category.education]: 0,
  [Category.health]: 0,
  [Category.money]: 0,
  [Category.work]: 0,
  [Category.technology]: 0,
  [Category.news]: 0,
  [Category.community]: 0,
  [Category.environments]: 0,
  [Category.culture]: 0,
  [Category.spirituality]: 0,
  [Category.freeTime]: 0,
};

export const questions: { [key: string]: Question } = {
  '1': {
    id: '1',
    question: '¿Cuáles son tus metas y sueños a corto plazo?',
    translationUS: 'What are your short-term goals and dreams?',
    category: Category.goals,
  },
  '2': {
    id: '2',
    question: '¿Cómo crees que tus metas y sueños afectan a tu vida diaria?',
    translationUS:
      'How do you think your goals and dreams affect your daily life?',
    category: Category.goals,
  },
  '3': {
    id: '3',
    question:
      '¿Cómo crees que tus metas y sueños afectan a tus valores y principios?',
    translationUS:
      'How do you think your goals and dreams affect your values and principles?',
    category: Category.goals,
  },
  '4': {
    id: '4',
    question: '¿Cómo piensas alcanzar tus metas y sueños?',
    translationUS: 'How do you plan to achieve your goals and dreams?',
    category: Category.goals,
  },
  '5': {
    id: '5',
    question: '¿Qué pasos estás tomando para lograr tus metas y sueños?',
    translationUS:
      'What steps are you taking to achieve your goals and dreams?',
    category: Category.goals,
  },
  '6': {
    id: '6',
    question: '¿Cómo te aseguras de que tus metas y sueños sean realistas?',
    translationUS:
      'How do you make sure that your goals and dreams are realistic?',
    category: Category.goals,
  },
  '7': {
    id: '7',
    question: '¿Cómo te adaptas a los cambios en tus metas y sueños?',
    translationUS: 'How do you adapt to changes in your goals and dreams?',
    category: Category.goals,
  },
  '8': {
    id: '8',
    question: '¿Cómo te sientes al lograr tus metas y sueños?',
    translationUS: 'How do you feel when you achieve your goals and dreams?',
    category: Category.goals,
  },
  '9': {
    id: '9',
    question: '¿Cómo te mantienes motivado para alcanzar tus metas y sueños?',
    translationUS:
      'How do you stay motivated to achieve your goals and dreams?',
    category: Category.goals,
  },
  '10': {
    id: '10',
    question:
      '¿Cómo te involucras en la comunidad para lograr tus metas y sueños?',
    translationUS:
      'How do you get involved in the community to achieve your goals and dreams?',
    category: Category.goals,
  },
  kjhf823h: {
    id: 'kjhf823h',
    question:
      '¿Cómo se manifiestan los principios fundamentales de la familia?',
    translationUS: `How do the family's fundamental principles manifest?`,
    category: Category.principles,
  },
  iuhf9084: {
    id: 'iuhf9084',
    question:
      '¿Qué crees que debemos hacer para lograr nuestros principios y valores?',
    translationUS:
      'What do you think we should do to achieve our principles and values?',
    category: Category.principles,
  },
  lkjhg890: {
    id: 'lkjhg890',
    question: '¿Qué significa para ti el respeto?',
    translationUS: 'What does respect mean to you?',
    category: Category.principles,
  },
  iuhg890: {
    id: 'iuhg890',
    question: '¿Qué significa para ti la honestidad?',
    translationUS: 'What does honesty mean to you?',
    category: Category.principles,
  },
  hjg890s: {
    id: 'hjg890s',
    question:
      '¿Cuáles son algunos de los valores que quieres enseñar a tus hijos?',
    translationUS:
      'What are some of the values you want to teach your children?',
    category: Category.principles,
  },
  rtj890d: {
    id: 'rtj890d',
    question: '¿De qué forma te afectan los principios familiares?',
    translationUS: 'How are you affected by family principles?',
    category: Category.principles,
  },
  yujh890h: {
    id: 'yujh890h',
    question: '¿Qué papel juegan los valores familiares en tu vida?',
    translationUS: 'What role do family values play in your life?',
    category: Category.principles,
  },
  kjhg890f: {
    id: 'kjhg890f',
    question:
      '¿Cómo podemos asegurarnos de que nuestros principios sean respetados?',
    translationUS: 'How can we make sure our principles are respected?',
    category: Category.principles,
  },
  iuhg890g: {
    id: 'iuhg890g',
    question: '¿Cómo podemos promover los valores familiares?',
    translationUS: 'How can we promote family values?',
    category: Category.principles,
  },
  lkjhg890h: {
    id: 'lkjhg890h',
    question: '¿Cómo define tu familia el respeto?',
    translationUS: 'How does your family define respect?',
    category: Category.principles,
  },
  aabbcc111: {
    id: 'aabbcc111',
    question: `¿Qué significa para ti el concepto de familia?`,
    translationUS: `What does family concept mean to you?`,
    category: Category.challenges,
  },
  ss22bc121: {
    id: 'ss22bc121',
    question: `¿Cómo está cambiando la familia a lo largo del tiempo?`,
    translationUS: `How is family changing over time?`,
    category: Category.challenges,
  },
  dss21cc32: {
    id: 'dss21cc32',
    question: `¿Cómo afectan los cambios en la familia a la vida personal?`,
    translationUS: `How do changes in family affect personal life?`,
    category: Category.challenges,
  },
  ssjj223311: {
    id: 'ssjj223311',
    question: `¿Cómo afectan las decisiones que tomas en la familia a tu vida personal?`,
    translationUS: `How do the decisions you make in family affect your personal life?`,
    category: Category.challenges,
  },
  aabbzz21c9: {
    id: 'aabbzz21c9',
    question: `¿Qué pasos puedes tomar para mejorar tus relaciones con miembros de la familia?`,
    translationUS: `What steps can you take to improve your relationships with family members?`,
    category: Category.challenges,
  },
  ccdd33444a: {
    id: 'ccdd33444a',
    question: `¿Cómo puedes aceptar y abrazar los cambios en la familia?`,
    translationUS: `How can you accept and embrace changes in family?`,
    category: Category.challenges,
  },
  dss22aabbb: {
    id: 'dss22aabbb',
    question: `¿Cómo puedes lidiar con los desafíos de la vida personal?`,
    translationUS: `How can you cope with personal life challenges?`,
    category: Category.challenges,
  },
  ccdd33444c: {
    id: 'ccdd33444c',
    question: `¿Cómo puedes prepararte para los cambios en la familia?`,
    translationUS: `How can you prepare for changes in family?`,
    category: Category.challenges,
  },
  eeff556677: {
    id: 'eeff556677',
    question: `¿Cómo puedes abordar los problemas en la familia?`,
    translationUS: `How can you tackle problems in family?`,
    category: Category.challenges,
  },
  gg11hh22ii: {
    id: 'gg11hh22ii',
    question: `¿Cómo puedes establecer límites saludables para proteger tu vida personal?`,
    translationUS: `How can you set healthy boundaries to protect your personal life?`,
    category: Category.challenges,
  },
  kx6gph890: {
    id: 'kx6gph890',
    question: `¿Cómo has pasado tu día?`,
    translationUS: `How has your day been?`,
    category: Category.relationships,
  },
  f6p9bz111: {
    id: 'f6p9bz111',
    question: `¿Cómo es la relación con tus hermanos?`,
    translationUS: `What is your relationship with your siblings like?`,
    category: Category.relationships,
  },
  '3u2gqv819': {
    id: '3u2gqv819',
    question: `¿Qué es lo que más te gusta de tus amigos?`,
    translationUS: `What do you like most about your friends?`,
    category: Category.relationships,
  },
  d5p7mq090: {
    id: 'd5p7mq090',
    question: `¿Cómo tratas a los demás?`,
    translationUS: `How do you treat others?`,
    category: Category.relationships,
  },
  gk9pfz819: {
    id: 'gk9pfz819',
    question: `¿Crees que la comunicación es importante?`,
    translationUS: `Do you think communication is important?`,
    category: Category.relationships,
  },
  f7b9pk767: {
    id: 'f7b9pk767',
    question: `¿Cómo se siente al establecer relaciones con otras personas?`,
    translationUS: `How do you feel when establishing relationships with other people?`,
    category: Category.relationships,
  },
  bz8pk7109: {
    id: 'bz8pk7109',
    question: `¿Cómo llevas tus problemas con tus seres queridos?`,
    translationUS: `How do you handle your problems with your loved ones?`,
    category: Category.relationships,
  },
  cz9gqf942: {
    id: 'cz9gqf942',
    question: `¿Crees que se debe tratar a los demás como desearías ser tratado?`,
    translationUS: `Do you believe in treating others as you wish to be treated?`,
    category: Category.relationships,
  },
  z2kf8g829: {
    id: 'z2kf8g829',
    question: `¿Creen que la comunicación es la clave para construir buenas relaciones?`,
    translationUS: `Do you believe that communication is the key to building good relationships?`,
    category: Category.relationships,
  },
  gk6f9q192: {
    id: 'gk6f9q192',
    question: `¿Cómo se sienten al hablar con personas desconocidas?`,
    translationUS: `How do you feel when speaking to strangers?`,
    category: Category.relationships,
  },
  aabbcd111: {
    id: 'aabbcd111',
    question: `¿Cómo podemos enseñar a nuestros hijos a ser buenos ciudadanos?`,
    translationUS: `How can we teach our children to be good citizens?`,
    category: Category.education,
  },
  ss22Zc121: {
    id: 'ss22Zc121',
    question: `¿Cómo puedes desarrollar tu creatividad?`,
    translationUS: `How can you develop your creativity?`,
    category: Category.education,
  },
  dd32aa321: {
    id: 'dd32aa321',
    question: `¿Qué tipo de habilidades se necesitan para tener éxito en la vida?`,
    translationUS: `What kind of skills are needed to succeed in life?`,
    category: Category.education,
  },
  ab12aa112: {
    id: 'ab12aa112',
    question: `¿Cómo puedes ayudar a tus hijos a aprender a lidiar con el fracaso?`,
    translationUS: `How can you help your children learn to deal with failure?`,
    category: Category.education,
  },
  ba21cc212: {
    id: 'ba21cc212',
    question: `¿Cómo puedes motivarte para tener éxito?`,
    translationUS: `How can you motivate yourself to succeed?`,
    category: Category.education,
  },
  aa11dc121: {
    id: 'aa11dc121',
    question: `¿Cómo podemos ayudar a nuestros hijos a desarrollar su autoestima?`,
    translationUS: `How can we help our children develop their self-esteem?`,
    category: Category.education,
  },
  cc22bb221: {
    id: 'cc22bb221',
    question: `¿Cómo podemos ayudar a nuestros hijos a desarrollar y mantener el respeto por sí mismos y los demás?`,
    translationUS: `How can we help our children develop and maintain respect for themselves and others?`,
    category: Category.education,
  },
  dd33cc331: {
    id: 'dd33cc331',
    question: `¿Cómo podemos enseñar a nuestros hijos el valor del trabajo duro?`,
    translationUS: `How can we teach our children the value of hard work?`,
    category: Category.education,
  },
  ee44dd441: {
    id: 'ee44dd441',
    question: `¿Cómo puedes ayudar a tus hijos a desarrollar habilidades de pensamiento crítico?`,
    translationUS: `How can you help your children develop critical thinking skills?`,
    category: Category.education,
  },
  ff55ee551: {
    id: 'ff55ee551',
    question: `¿Cómo puedes ayudar a tus hijos a desarrollar su habilidad para tomar decisiones?`,
    translationUS: `How can you help your children develop their decision-making skills?`,
    category: Category.education,
  },
  aabbhc111: {
    id: 'aabbhc111',
    question: '¿Cuál es tu ejercicio favorito?',
    translationUS: 'What is your favorite exercise?',
    category: Category.health,
  },
  ss42bc121: {
    id: 'ss42bc121',
    question: '¿Cómo te sientes hoy?',
    translationUS: 'How are you feeling today?',
    category: Category.health,
  },
  qw11er121: {
    id: 'qw11er121',
    question: '¿Cómo manejas el estrés?',
    translationUS: 'How do you manage stress?',
    category: Category.health,
  },
  zc22xz121: {
    id: 'zc22xz121',
    question: '¿Cuál es tu comida saludable favorita?',
    translationUS: 'What is your favorite healthy food?',
    category: Category.health,
  },
  mn33gh121: {
    id: 'mn33gh121',
    question: '¿Cuál es tu rutina de mañana para comenzar el día con energía?',
    translationUS: 'What is your morning routine to start the day with energy?',
    category: Category.health,
  },
  as44df121: {
    id: 'as44df121',
    question: '¿Cuál es tu estrategia para dormir mejor?',
    translationUS: 'What is your strategy for sleeping better?',
    category: Category.health,
  },
  gh55jk121: {
    id: 'gh55jk121',
    question: '¿Cómo te aseguras de mantener una dieta equilibrada?',
    translationUS: 'How do you ensure a balanced diet?',
    category: Category.health,
  },
  ty66ui121: {
    id: 'ty66ui121',
    question: '¿Qué haces para relajarte?',
    translationUS: 'What do you do to relax?',
    category: Category.health,
  },
  io77op121: {
    id: 'io77op121',
    question: '¿Cuál es tu técnica de meditación preferida?',
    translationUS: 'What is your favorite meditation technique?',
    category: Category.health,
  },
  qw88er121: {
    id: 'qw88er121',
    question: '¿Cómo te ayuda el deporte a mantener tu salud mental?',
    translationUS: 'How does sports help you maintain your mental health?',
    category: Category.health,
  },
  aabbcc311: {
    id: 'aabbcc311',
    question: `¿Cómo manejas tus finanzas?`,
    translationUS: `How do you manage your finances?`,
    category: Category.money,
  },
  ss22bc122: {
    id: 'ss22bc122',
    question: `¿Qué tan a menudo llevas un presupuesto?`,
    translationUS: `How often do you keep a budget?`,
    category: Category.money,
  },
  jhgf1121: {
    id: 'jhgf1121',
    question: `¿Qué es la tasa de ahorro?`,
    translationUS: `What is the savings rate?`,
    category: Category.money,
  },
  poi98765: {
    id: 'poi98765',
    question: `¿Cómo planeas tus gastos?`,
    translationUS: `How do you plan your expenses?`,
    category: Category.money,
  },
  jhgf1233: {
    id: 'jhgf1233',
    question: `¿Cómo puedes reducir los gastos?`,
    translationUS: `How can you reduce expenses?`,
    category: Category.money,
  },
  qwerty13: {
    id: 'qwerty13',
    question: `¿Cómo puedes ahorrar dinero?`,
    translationUS: `How can you save money?`,
    category: Category.money,
  },
  asd4586: {
    id: 'asd4586',
    question: `¿Cómo puedes pagar tus deudas?`,
    translationUS: `How can you pay off your debts?`,
    category: Category.money,
  },
  poi90876: {
    id: 'poi90876',
    question: `¿Cómo puedes administrar tus finanzas personales?`,
    translationUS: `How can you manage your personal finances?`,
    category: Category.money,
  },
  jhgf1222: {
    id: 'jhgf1222',
    question: `¿Cómo puedes invertir tu dinero?`,
    translationUS: `How can you invest your money?`,
    category: Category.money,
  },
  qwerty11: {
    id: 'qwerty11',
    question: `¿Cómo puedes ganar más dinero?`,
    translationUS: `How can you make more money?`,
    category: Category.money,
  },
  hj2wfj1: {
    id: 'hj2wfj1',
    question: `¿Qué habilidades necesitas desarrollar para avanzar en tu carrera?`,
    translationUS: `What skills do you need to develop to progress in your career?`,
    category: Category.work,
  },
  k1m23c1: {
    id: 'k1m23c1',
    question: `¿Cómo puedo mejorar mi marca profesional?`,
    translationUS: `How can I improve my professional brand?`,
    category: Category.work,
  },
  n4jksc1: {
    id: 'n4jksc1',
    question: `¿Cómo me aseguro de que estoy en el camino correcto para alcanzar mis metas profesionales?`,
    translationUS: `How do I make sure I'm on the right track to achieve my professional goals?`,
    category: Category.work,
  },
  m2d4s2: {
    id: 'm2d4s2',
    question: `¿Cómo puedo equilibrar mis responsabilidades laborales y mi vida personal?`,
    translationUS: `How can I balance my work responsibilities and my personal life?`,
    category: Category.work,
  },
  i3lkf3: {
    id: 'i3lkf3',
    question: `¿Cómo puedo mejorar mi confianza en mi carrera?`,
    translationUS: `How can I boost my confidence in my career?`,
    category: Category.work,
  },
  f2d3e2: {
    id: 'f2d3e2',
    question: `¿Cómo puedo encontrar un mentor para ayudarme a desarrollar mis habilidades profesionales?`,
    translationUS: `How can I find a mentor to help me develop my professional skills?`,
    category: Category.work,
  },
  k1d2f1: {
    id: 'k1d2f1',
    question: `¿Qué debo hacer si estoy estancado en mi carrera?`,
    translationUS: `What should I do if I'm stuck in my career?`,
    category: Category.work,
  },
  f2s3e1: {
    id: 'f2s3e1',
    question: `¿Cómo puedo mejorar mi presencia en línea?`,
    translationUS: `How can I improve my online presence?`,
    category: Category.work,
  },
  e2w3f1: {
    id: 'e2w3f1',
    question: `¿Cómo puedo mejorar mi currículum para obtener un mejor trabajo?`,
    translationUS: `How can I improve my resume to get a better job?`,
    category: Category.work,
  },
  d2k3e1: {
    id: 'd2k3e1',
    question: `¿Cómo puedo mejorar mi liderazgo en la oficina?`,
    translationUS: `How can I improve my leadership in the office?`,
    category: Category.work,
  },
  qw3hud4s: {
    id: 'qw3hud4s',
    question: `¿Cómo se usa la inteligencia artificial para mejorar la vida diaria?`,
    translationUS: `How is Artificial Intelligence used to improve daily life?`,
    category: Category.technology,
  },
  '8fvxzc5t': {
    id: '8fvxzc5t',
    question: `¿Qué avances tecnológicos se han hecho en los últimos años?`,
    translationUS: `What technological advancements have been made in recent years?`,
    category: Category.technology,
  },
  '2yjhwk9u': {
    id: '2yjhwk9u',
    question: `¿Cómo la tecnología está cambiando la forma en que vivimos?`,
    translationUS: `How is technology changing the way we live?`,
    category: Category.technology,
  },
  lft6bz8a: {
    id: 'lft6bz8a',
    question: `¿Qué tecnologías son útiles en el trabajo?`,
    translationUS: `What technologies are useful in the workplace?`,
    category: Category.technology,
  },
  pwzskm3j: {
    id: 'pwzskm3j',
    question: `¿Cómo la computación en la nube está transformando los negocios?`,
    translationUS: `How is cloud computing transforming businesses?`,
    category: Category.technology,
  },
  '9xh27jd6': {
    id: '9xh27jd6',
    question: `¿Cómo los dispositivos móviles están cambiando el entretenimiento?`,
    translationUS: `How are mobile devices changing entertainment?`,
    category: Category.technology,
  },
  wmt2r8u1: {
    id: 'wmt2r8u1',
    question: `¿Qué avances se han hecho en tecnología de inteligencia artificial?`,
    translationUS: `What advancements have been made in artificial intelligence technology?`,
    category: Category.technology,
  },
  zk4jdg7a: {
    id: 'zk4jdg7a',
    question: `¿Cómo la robótica está transformando la manufactura?`,
    translationUS: `How is robotics transforming manufacturing?`,
    category: Category.technology,
  },
  s6jg9mb2: {
    id: 's6jg9mb2',
    question: `¿Cómo la tecnología está cambiando la forma en que nos comunicamos?`,
    translationUS: `How is technology changing the way we communicate?`,
    category: Category.technology,
  },
  '7xrwqf3u': {
    id: '7xrwqf3u',
    question: `¿Cómo la realidad aumentada está transformando la manera en que experimentamos el mundo?`,
    translationUS: `How is augmented reality transforming the way we experience the world?`,
    category: Category.technology,
  },
  dssd33sss: {
    id: 'dssd33sss',
    question: `¿Cuáles son los últimos acontecimientos en el mundo?`,
    translationUS: `What are the latest events in the world?`,
    category: Category.news,
  },
  aabb2233d: {
    id: 'aabb2233d',
    question: `¿Qué impacto tiene el cambio climático en el mundo?`,
    translationUS: `What impact does climate change have on the world?`,
    category: Category.news,
  },
  ccddee124: {
    id: 'ccddee124',
    question: `¿Qué se sabe sobre el virus nuevo?`,
    translationUS: `What is known about the new virus?`,
    category: Category.news,
  },
  bbeessd11: {
    id: 'bbeessd11',
    question: `¿Cómo están los derechos humanos en el mundo?`,
    translationUS: `How are human rights in the world?`,
    category: Category.news,
  },
  ffgg2233a: {
    id: 'ffgg2233a',
    question: `¿Cómo afecta la economía mundial la pandemia?`,
    translationUS: `How does the global economy affect the pandemic?`,
    category: Category.news,
  },
  ccddee123: {
    id: 'ccddee123',
    question: `¿Cómo afecta la desigualdad en el mundo?`,
    translationUS: `How does inequality affect the world?`,
    category: Category.news,
  },
  aabblle11: {
    id: 'aabblle11',
    question: `¿Cómo está la situación de la educación en el mundo?`,
    translationUS: `How is the situation of education in the world?`,
    category: Category.news,
  },
  kkjjcc122: {
    id: 'kkjjcc122',
    question: `¿Qué medidas están tomando los gobiernos para combatir el cambio climático?`,
    translationUS: `What measures are governments taking to combat climate change?`,
    category: Category.news,
  },
  bbddaatt1: {
    id: 'bbddaatt1',
    question: `¿Qué efectos tiene la tecnología en la sociedad?`,
    translationUS: `What effects does technology have on society?`,
    category: Category.news,
  },
  aaeeffgg1: {
    id: 'aaeeffgg1',
    question: `¿Qué consecuencias trae la globalización?`,
    translationUS: `What consequences does globalization bring?`,
    category: Category.news,
  },
  fhg45klj: {
    id: 'fhg45klj',
    question: `¿Cómo puedes contribuir a la comunidad?`,
    translationUS: `How can you contribute to the community?`,
    category: Category.community,
  },
  pq567983: {
    id: 'pq567983',
    question: `¿Cómo se puede promover la responsabilidad social?`,
    translationUS: `How can social responsibility be promoted?`,
    category: Category.community,
  },
  lmn456op: {
    id: 'lmn456op',
    question: `¿Qué puedes hacer para promover una cultura de responsabilidad?`,
    translationUS: `What can you do to promote a culture of responsibility?`,
    category: Category.community,
  },
  qwertyu1: {
    id: 'qwertyu1',
    question: `¿Qué consejos puedes dar para fomentar el compromiso con la comunidad?`,
    translationUS: `What advice can you give to foster commitment to the community?`,
    category: Category.community,
  },
  asdfghj2: {
    id: 'asdfghj2',
    question: `¿Cómo puedes incentivar el trabajo en equipo para mejorar la comunidad?`,
    translationUS: `How can you encourage teamwork to improve the community?`,
    category: Category.community,
  },
  zxcvbnm3: {
    id: 'zxcvbnm3',
    question: `¿Cómo se puede promover el compromiso con la comunidad local?`,
    translationUS: `How can commitment to the local community be promoted?`,
    category: Category.community,
  },
  poiuyt12: {
    id: 'poiuyt12',
    question: `¿Cuáles son algunas acciones concretas que los miembros de la comunidad pueden tomar para mejorarla?`,
    translationUS: `What are some concrete actions that community members can take to improve it?`,
    category: Category.community,
  },
  lkjhgf34: {
    id: 'lkjhgf34',
    question: `¿Cómo se puede lograr el compromiso de todos los miembros de la comunidad?`,
    translationUS: `How can commitment from all members of the community be achieved?`,
    category: Category.community,
  },
  mnbvcxz5: {
    id: 'mnbvcxz5',
    question: `¿Cómo puedes promover el trabajo en equipo entre los miembros de la comunidad?`,
    translationUS: `How can you promote teamwork among members of the community?`,
    category: Category.community,
  },
  yuiop987: {
    id: 'yuiop987',
    question: `¿Cómo se puede ayudar a la comunidad a comprometerse con la responsabilidad social?`,
    translationUS: `How can the community be helped to commit to social responsibility?`,
    category: Category.community,
  },
  aabbcc11s: {
    id: 'aabbcc11s',
    question: `¿Qué es la huella ecológica?`,
    translationUS: `What is the ecological footprint?`,
    category: Category.environments,
  },
  ss22bc141: {
    id: 'ss22bc141',
    question: `¿Qué significa "reducir, reusar y reciclar"?`,
    translationUS: `What does "reduce, reuse and recycle" mean?`,
    category: Category.environments,
  },
  asd34hf12: {
    id: 'asd34hf12',
    question: `¿Qué son los combustibles fósiles?`,
    translationUS: `What are fossil fuels?`,
    category: Category.environments,
  },
  hjk08dk21: {
    id: 'hjk08dk21',
    question: `¿Qué es el cambio climático?`,
    translationUS: `What is climate change?`,
    category: Category.environments,
  },
  sdj12ke92: {
    id: 'sdj12ke92',
    question: `¿Cómo podemos reducir nuestra huella de carbono?`,
    translationUS: `How can we reduce our carbon footprint?`,
    category: Category.environments,
  },
  das12bn21: {
    id: 'das12bn21',
    question: `¿Por qué la biodiversidad es importante?`,
    translationUS: `Why is biodiversity important?`,
    category: Category.environments,
  },
  fhg56jm22: {
    id: 'fhg56jm22',
    question: `¿Qué son los recursos naturales renovables?`,
    translationUS: `What are renewable natural resources?`,
    category: Category.environments,
  },
  gfh09lm10: {
    id: 'gfh09lm10',
    question: `¿Qué son los recursos naturales no renovables?`,
    translationUS: `What are non-renewable natural resources?`,
    category: Category.environments,
  },
  hjy75ls21: {
    id: 'hjy75ls21',
    question: `¿Cuáles son las principales fuentes de energía renovable?`,
    translationUS: `What are the main sources of renewable energy?`,
    category: Category.environments,
  },
  sdk09ls92: {
    id: 'sdk09ls92',
    question: `¿Cómo podemos evitar la contaminación del aire?`,
    translationUS: `How can we prevent air pollution?`,
    category: Category.environments,
  },
  mjb4dz00: {
    id: 'mjb4dz00',
    question: `¿Cuáles son tus raíces culturales?`,
    translationUS: `What are your cultural roots?`,
    category: Category.culture,
  },
  h9j8i1k2: {
    id: 'h9j8i1k2',
    question: `¿Cómo honras y compartes tu cultura?`,
    translationUS: `How do you honor and share your culture?`,
    category: Category.culture,
  },
  c7jd97y1: {
    id: 'c7jd97y1',
    question: `¿Cuáles son los aspectos más importantes de tu cultura?`,
    translationUS: `What are the most important aspects of your culture?`,
    category: Category.culture,
  },
  r37kf2l6: {
    id: 'r37kf2l6',
    question: `¿Cómo celebras los logros de tu cultura?`,
    translationUS: `How do you celebrate your culture’s accomplishments?`,
    category: Category.culture,
  },
  e8d4g7m4: {
    id: 'e8d4g7m4',
    question: `¿Cómo has contribuido a la celebración de la diversidad?`,
    translationUS: `How have you contributed to celebrating diversity?`,
    category: Category.culture,
  },
  w2f3q0i7: {
    id: 'w2f3q0i7',
    question: `¿Cómo se puede aprender más sobre la cultura de alguien?`,
    translationUS: `How can one learn more about someone’s culture?`,
    category: Category.culture,
  },
  f4k7d0x2: {
    id: 'f4k7d0x2',
    question: `¿Cómo has abrazado la diversidad en tu vida?`,
    translationUS: `How have you embraced diversity in your life?`,
    category: Category.culture,
  },
  s1j2c6h3: {
    id: 's1j2c6h3',
    question: `¿Cómo has aprendido de formas de vida diferentes?`,
    translationUS: `How have you learned from different ways of life?`,
    category: Category.culture,
  },
  m9p3l1q3: {
    id: 'm9p3l1q3',
    question: `¿Qué haces para ayudar a otros a comprender la diversidad?`,
    translationUS: `What do you do to help others understand diversity?`,
    category: Category.culture,
  },
  k2x1g7z8: {
    id: 'k2x1g7z8',
    question: `¿Cómo puedes promover la diversidad en tu comunidad?`,
    translationUS: `How can you promote diversity in your community?`,
    category: Category.culture,
  },
  fdh123ghf: {
    id: 'fdh123ghf',
    question: `¿Cuál es el mayor regalo que Dios nos ha dado?`,
    translationUS: `What is the greatest gift God has given us?`,
    category: Category.spirituality,
  },
  fhg321hjf: {
    id: 'fhg321hjf',
    question: `¿Cuál es el mayor desafío de la vida?`,
    translationUS: `What is the greatest challenge of life?`,
    category: Category.spirituality,
  },
  kjh231fhg: {
    id: 'kjh231fhg',
    question: `¿Cómo podemos cultivar el amor y la compasión?`,
    translationUS: `How can we cultivate love and compassion?`,
    category: Category.spirituality,
  },
  jhg123fhg: {
    id: 'jhg123fhg',
    question: `¿Cómo podemos perdonar a alguien que nos ha hecho daño?`,
    translationUS: `How can we forgive someone who has hurt us?`,
    category: Category.spirituality,
  },
  fgh123fjh: {
    id: 'fgh123fjh',
    question: `¿Cómo podemos honrar a nuestros ancestros?`,
    translationUS: `How can we honor our ancestors?`,
    category: Category.spirituality,
  },
  hjg213ghf: {
    id: 'hjg213ghf',
    question: `¿Cómo podemos cultivar la gratitud?`,
    translationUS: `How can we cultivate gratitude?`,
    category: Category.spirituality,
  },
  fgh123fhg: {
    id: 'fgh123fhg',
    question: `¿Cómo podemos estar en armonía con el mundo que nos rodea?`,
    translationUS: `How can we be in harmony with the world around us?`,
    category: Category.spirituality,
  },
  fhg123hjf: {
    id: 'fhg123hjf',
    question: `¿Cómo podemos aprender a aceptar nuestras imperfecciones?`,
    translationUS: `How can we learn to accept our imperfections?`,
    category: Category.spirituality,
  },
  fgh123jhg: {
    id: 'fgh123jhg',
    question: `¿Cómo podemos cultivar la humildad?`,
    translationUS: `How can we cultivate humility?`,
    category: Category.spirituality,
  },
  fgh123hjg: {
    id: 'fgh123hjg',
    question: `¿Cómo podemos cultivar el respeto?`,
    translationUS: `How can we cultivate respect?`,
    category: Category.spirituality,
  },
  sdfs9s90s: {
    id: 'sdfs9s90s',
    question: `¿Cuáles son algunas maneras de mantenerse ocupado en tu tiempo libre?`,
    translationUS: `What are some ways to keep yourself busy in your free time?`,
    category: Category.freeTime,
  },
  sdfs98s90: {
    id: 'sdfs98s90',
    question: `¿Cómo podemos usar el tiempo libre para mejorar nuestras habilidades?`,
    translationUS: `How can we use free time to improve our skills?`,
    category: Category.freeTime,
  },
  sdfs9s99s: {
    id: 'sdfs9s99s',
    question: `¿Qué actividades son buenas para relajarse durante el tiempo libre?`,
    translationUS: `What activities are good for relaxing during free time?`,
    category: Category.freeTime,
  },
  sdfs9s90x: {
    id: 'sdfs9s90x',
    question: `¿Cuáles son algunas formas de disfrutar el tiempo libre sin gastar mucho dinero?`,
    translationUS: `What are some ways to enjoy free time without spending a lot of money?`,
    category: Category.freeTime,
  },
  sdfs9s90w: {
    id: 'sdfs9s90w',
    question: `¿Cuáles son algunos buenos consejos para planificar y organizar el tiempo libre?`,
    translationUS: `What are some good tips for planning and organizing free time?`,
    category: Category.freeTime,
  },
  sdfs9s90n: {
    id: 'sdfs9s90n',
    question: `¿Cómo puedes usar tu tiempo libre para mejorar tu salud mental?`,
    translationUS: `How can you use your free time to improve your mental health?`,
    category: Category.freeTime,
  },
  sdfs9s90m: {
    id: 'sdfs9s90m',
    question: `¿Cómo podemos usar el tiempo libre para conocer mejor a nuestras familias?`,
    translationUS: `How can we use free time to get to know our families better?`,
    category: Category.freeTime,
  },
  sdfs9s90o: {
    id: 'sdfs9s90o',
    question: `¿Cómo podemos usar el tiempo libre para descubrir nuevas áreas de interés?`,
    translationUS: `How can we use free time to discover new areas of interest?`,
    category: Category.freeTime,
  },
  sdfs9s90p: {
    id: 'sdfs9s90p',
    question: `¿Cuáles son algunas buenas formas de aprender cosas nuevas durante el tiempo libre?`,
    translationUS: `What are some good ways to learn new things during free time?`,
    category: Category.freeTime,
  },
  sdfs9s90q: {
    id: 'sdfs9s90q',
    question: `¿Cómo podemos usar el tiempo libre para mejorar nuestras relaciones con los demás?`,
    translationUS: `How can we use free time to improve our relationships with others?`,
    category: Category.freeTime,
  },
};
