export const questions = [
  '¿Qué lugares has visitado últimamente?',
  '¿Cuál ha sido tu destino de viaje favorito hasta ahora?',
  '¿Hay algún lugar del mundo al que te gustaría viajar algún día?',
  '¿Cómo te sientes cuando viajas a lugares nuevos?',
  '¿Has tenido alguna experiencia inolvidable mientras viajabas?',
  '¿Cuáles son tus pasatiempos o hobbies favoritos?',
  '¿Cómo te sientes cuando practicas tus pasatiempos o hobbies?',
  '¿Hay algún hobby o pasatiempo que te gustaría probar?',
  '¿Has aprendido algo nuevo gracias a tus pasatiempos o hobbies?',
  '¿Cómo compartes tus pasatiempos o hobbies con amigos o familiares?',
  '¿Cuál es tu trabajo o profesión actual?',
  '¿Te gusta tu trabajo o tienes planes de cambiar de carrera en el futuro?',
  '¿Qué habilidades o conocimientos has adquirido gracias a tu trabajo?',
  '¿Hay algún logro laboral del que estés especialmente orgulloso?',
  '¿Cómo te sientes acerca de tu progreso profesional hasta ahora?',
  '¿Cómo te llevas con tus padres y hermanos?',
  '¿Tienes una familia grande o pequeña?',
  '¿Hay algún miembro de tu familia con el que tengas una relación especialmente cercana?',
  '¿Hay algún consejo o lección que hayas aprendido de tu familia?',
  '¿Cómo te sientes acerca de tu relación actual con tu familia?',
  '¿Cuidas tu salud de alguna manera especial, como hacer ejercicio o seguir una dieta determinada?',
  '¿Hay algún hábito de vida saludable que te gustaría incorporar a tu rutina?',
  '¿Te sientes bien consigo mismo y con tu cuerpo?',
  '¿Hay algún desafío de salud que hayas enfrentado en el pasado o actualmente?',
  '¿Cómo te sientes acerca de tu bienestar general y cómo lo mantienes ?',
  '¿Qué estudias o qué estudiaste en el pasado?',
  '¿Hay algún campo de estudio que te interese especialmente?',
  '¿Has aprendido algo nuevo últimamente?',
  '¿Hay algún tema o materia que te resulte especialmente difícil de entender?',
  '¿Cómo te sientes acerca de tu progreso académico o de aprendizaje?',
  '¿Qué tipo de películas, libros o música te gusta?',
  '¿Hay algún evento cultural o de entretenimiento al que hayas asistido recientemente y te haya gustado especialmente?',
  '¿Te gusta salir a ver obras de teatro, conciertos o exposiciones?',
  '¿Hay algún artista o grupo que admire especialmente?',
  '¿Cómo te sientes cuando disfrutas de la cultura y el entretenimiento?',
  '¿Te interesas por la política y la actualidad?',
  '¿Hay algún tema político o de actualidad que te preocupe especialmente?',
  '¿Has participado en alguna forma en la vida política o en la toma de decisiones en tu comunidad?',
  '¿Hay algún cambio o reforma que te gustaría ver en tu país o en el mundo?',
  '¿Cómo te sientes acerca de la forma en que se toman las decisiones políticas y cómo afectan a tu vida y a la de otros?',
  '¿Te gusta practicar algún deporte o hacer actividad física?',
  '¿Hay algún deporte o actividad física que te guste especialmente?',
  '¿Te sientes motivado para hacer ejercicio y mantenerte activo?',
  '¿Has tenido alguna lesión o problema de salud relacionado con la actividad física?',
  '¿Cómo te sientes cuando haces ejercicio o practicas deportes?',
  '¿Hay algo de ti mismo que te guste especialmente?',
  '¿Hay algún cambio o mejora personal que te gustaría hacer?',
  '¿Cómo te sientes acerca de tu propio progreso y desarrollo personal?',
  '¿Hay algún consejo o lección que hayas aprendido sobre ti mismo en el pasado?',
  '¿Hay algún sueño o meta personal que quieras alcanzar en elfuturo?',
  '¿Te interesas por la tecnología y la ciencia?',
  '¿Hay algún avance tecnológico o descubrimiento científico que te haya impresionado recientemente?',
  '¿Hay algún campo de la tecnología o la ciencia que te interese especialmente?',
  '¿Has utilizado algún dispositivo o aplicación nueva últimamente?',
  '¿Cómo te sientes acerca de la forma en que la tecnología y la ciencia afectan a tu vida y al mundo en general?',
  '¿Te interesas por la moda y el estilo personal?',
  '¿Hay algún diseñador o marca que te guste especialmente?',
  '¿Cómo te sientes acerca de tu propio estilo y de cómo te vistes?',
  '¿Hay algún estilo o tendencia que te gustaría probar?',
  '¿Cómo sientes que tu estilo y elección de ropa refleja tu personalidad?',
  '¿Te gusta cocinar o te interesan los alimentos y la gastronomía?',
  '¿Hay algún plato o tipo de comida que te guste especialmente?',
  '¿Has probado algún plato o ingrediente nuevo últimamente?',
  '¿Hay algún tipo de comida o cocina que te gustaría aprender a preparar?',
  '¿Cómo te sientes acerca de tu relación con la comida y la forma en que comes?',
];
